### ISSUE TITLE
[Bug]: Shared volume issue in RWX mode

### ISSUE THREAD

**Issue by benderbandolero** [kadalu/kadalu#1021]
**Describe the bug**
I have a deployment using kadalu volume in RWX mode.
When a container write a file (update the content) on the volume, the another instances of the deployment  doesn't have the new version of the file.

**To Reproduce**
1. Create kadalu volume on RWX mode
2. Create deployment with at least 3 replicas
3. Exec bash/sh in the pods
4. Create a file and modify the content
5. Check the file on other instance

**Expected behavior**
The content file should be the same everywhere

**Actual behavior**
Sometimes, the another pods have not the latest content.
When I scale up my replicas to 4, the new pod have the correct content

**Environment:**
 - Kadalu Version: 1.1.0
 - K8S_DIST: kubernetes 1.23.8

**Screenshots or Logs**

**Additional context**
If I check the content of the file:
```shell 
$ for pods in wiwi-tools-54cbb4f465-cgbr7 wiwi-tools-54cbb4f465-lz5g8 wiwi-tools-54cbb4f465-xxngp wiwi-tools-54cbb4f465-zxdkr; do kubectl -n default exec -it $pods -c wiwi-tools -- md5sum /data/bl
a ; done
59bcc3ad6775562f845953cf01624225  /data/bla
3cd7a0db76ff9dca48979e24c39b408c  /data/bla
59bcc3ad6775562f845953cf01624225  /data/bla
3cd7a0db76ff9dca48979e24c39b408c  /data/bla
 # for pods in wiwi-tools-54cbb4f465-cgbr7 wiwi-tools-54cbb4f465-lz5g8 wiwi-tools-54cbb4f465-hx5sb wiwi-tools-54cbb4f465-zxdkr; do kubectl -n default exec -it $pods -c wiwi-tools -- cat /data/bla ; done
lol
bla
lol
bla
```
```shell
# kubectl -n default describe pvc kadalu-vol-data
Name:          kadalu-vol-data
Namespace:     default
StorageClass:  kadalu.storage-pool
Status:        Bound
Volume:        pvc-0122b38a-febc-409f-a093-32d5cbd12fe6
Labels:        app=wiwi-tools
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: kadalu
               volume.kubernetes.io/storage-provisioner: kadalu
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      954Mi
Access Modes:  RWX
VolumeMode:    Filesystem
Used By:       wiwi-tools-54cbb4f465-cgbr7
               wiwi-tools-54cbb4f465-hx5sb
               wiwi-tools-54cbb4f465-lz5g8
               wiwi-tools-54cbb4f465-zxdkr
Events:        <none>
```
```shell
# for pods in wiwi-tools-54cbb4f465-cgbr7 wiwi-tools-54cbb4f465-lz5g8 wiwi-tools-54cbb4f465-hx5sb  wiwi-tools-54cbb4f465-zxdkr; do kubectl -n default exec -it $pods -c wiwi-tools -- df -h /data ; done
Filesystem                Size      Used Available Use% Mounted on
kadalu:storage-pool     953.7M      1.8M    951.9M   0% /data
Filesystem                Size      Used Available Use% Mounted on
kadalu:storage-pool     953.7M      1.8M    951.9M   0% /data
Filesystem                Size      Used Available Use% Mounted on
kadalu:storage-pool     953.7M      1.8M    951.9M   0% /data
Filesystem                Size      Used Available Use% Mounted on
kadalu:storage-pool     953.7M      1.8M    951.9M   0% /data
```
```shell
# kubectl -n default describe deploy wiwi-tools
Name:               wiwi-tools
Namespace:          default
CreationTimestamp:  Wed, 20 Sep 2023 14:23:34 +0000
Labels:             app=wiwi-tools
Annotations:        deployment.kubernetes.io/revision: 1
Selector:           app=wiwi-tools
Replicas:           4 desired | 4 updated | 4 total | 4 available | 0 unavailable
StrategyType:       Recreate
MinReadySeconds:    0
Pod Template:
  Labels:  app=wiwi-tools
  Containers:
   wiwi-tools:
    Image:      alpine:latest
    Port:       <none>
    Host Port:  <none>
    Command:
      sleep
      infinity
    Environment:  <none>
    Mounts:
      /data/ from data-kadalu (rw)
  Volumes:
   apiserver-data-kadalu:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  kadalu-vol-data
    ReadOnly:   false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   wiwi-tools-54cbb4f465 (4/4 replicas created)
Events:          <none>
```

Do you have the same issue ?

Regards

**Comment by benderbandolero** [comment]
Hello, 

Do you have any idea about the issue ? 

Regards

**Comment by benderbandolero** [comment]
Hello,

I've upgraded my cluster to Kadalu 1.2.0 version and the problem still persist :(
I've also tested with another Kubernetes version (1.23.8 and 1.27.5)

Regards

**Comment by couloum** [comment]
Hello,

I've recorded a session where we reproduced the issue. This will maybe bring some clarity over it.

![Kadalu issue](https://github.com/kadalu/kadalu/assets/600871/9e100474-e202-4d75-944b-0644c40058bd)

This was tested on Kubernetes 1.27.5 and Kadalu 0.8.15, but we reproduced the issue on all version of Kadalu up to 1.2.0.

I'm very surprised about this issue as it seems very critical. Until now it didn't impact us. Maybe we didn't have use cases where the issue could really create applicative problems. It appeared when we migrate a specific application storage from Heketi to Kadalu, where we have a lot of replica (more than 10) and the application heavily rely on files being synced.

I'm wondering if the issue is more a Kadalu issue or a glusterfs issue.

If anyone is able to reproduce this in a test environment, it would already be a great answer as it would confirm that the issue does not come from a specific setup from us.

Thank you

**Comment by liyuntao** [comment]
Hi @benderbandolero 

> Sometimes, the another pods have not the latest content.
 
Does it actually same latest content when pods is on the same node?

**Comment by leelavg** [comment]
- Unfortunately, I'm unable to reproduce the scenario
- the commands and corresponding description are a little bit off in the cast, however the scenario still remains the same
- ref
```
# k version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.4
Kustomize Version: v5.0.1
Server Version: v1.27.6+b49f9d1

# curl -sL https://github.com/kadalu/kadalu/releases/download/1.2.0/kadalu-operator-openshift.yaml | sed 's/"no"/"yes"/' | k apply -f -
customresourcedefinition.apiextensions.k8s.io/kadalustorages.kadalu-operator.storage unchanged
namespace/kadalu created
serviceaccount/kadalu-operator created
serviceaccount/kadalu-csi-nodeplugin created
serviceaccount/kadalu-csi-provisioner created
serviceaccount/kadalu-server-sa created
clusterrole.rbac.authorization.k8s.io/kadalu-operator created
clusterrole.rbac.authorization.k8s.io/kadalu-csi-external-attacher created
clusterrole.rbac.authorization.k8s.io/kadalu-csi-external-provisioner created
clusterrole.rbac.authorization.k8s.io/kadalu-csi-external-resizer created
clusterrolebinding.rbac.authorization.k8s.io/kadalu-operator created
clusterrolebinding.rbac.authorization.k8s.io/kadalu-csi-external-attacher created
clusterrolebinding.rbac.authorization.k8s.io/kadalu-csi-external-provisioner created
clusterrolebinding.rbac.authorization.k8s.io/kadalu-csi-external-resizer created
role.rbac.authorization.k8s.io/kadalu-operator created
rolebinding.rbac.authorization.k8s.io/kadalu-operator created
Warning: would violate PodSecurity "restricted:v1.24": privileged (container "kadalu-operator" must not set securityContext.privileged=true), allowPrivilegeEscalation != false (container "kadalu-operator" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "kadalu-operator" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "kadalu-operator" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "kadalu-operator" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
deployment.apps/operator created
securitycontextconstraints.security.openshift.io/kadalu-scc created

# curl -sL https://github.com/kadalu/kadalu/releases/download/1.2.0/csi-nodeplugin-openshift.yaml | sed 's/"no"/"yes"/' | k apply -f -                        
clusterrole.rbac.authorization.k8s.io/kadalu-csi-nodeplugin created
clusterrolebinding.rbac.authorization.k8s.io/kadalu-csi-nodeplugin created
daemonset.apps/kadalu-csi-nodeplugin created
```
``` json
# k get kds pool -ojsonpath='{.spec}' | jq
{
  "pvReclaimPolicy": "delete",
  "single_pv_per_pool": false,
  "storage": [
    {
      "device": "/dev/loop0",
      "node": "ip-10-0-16-104.us-east-2.compute.internal"
    },
    {
      "device": "/dev/loop0",
      "node": "ip-10-0-50-78.us-east-2.compute.internal"
    },
    {
      "device": "/dev/loop0",
      "node": "ip-10-0-78-34.us-east-2.compute.internal"
    }
  ],
  "type": "Replica3"
}
```
``` yaml
# cat /tmp/dep.yaml
# -*- mode: yaml -*-
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-io
spec:
  storageClassName: kadalu.pool
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: io-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: io-app
  template:
    metadata:
      labels:
        app: io-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - io-app
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: io-pod
        image: docker.io/kadalu/test-io:devel
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo "Ready!" && /usr/bin/tail -f /dev/null']
        volumeMounts:
        - mountPath: '/mnt/alpha'
          name: csivol
        livenessProbe:
          exec:
            command:
              - 'sh'
              - '-ec'
              - 'df'
          initialDelaySeconds: 3
          periodSeconds: 3
      volumes:
      - name: csivol
        persistentVolumeClaim:
          claimName: pv-io
```
```
# k get po -owide -lapp
NAME                      READY   STATUS    RESTARTS   AGE   IP            NODE                                        NOMINATED NODE   READINESS GATES
io-app-78c4f8b784-4rjql   1/1     Running   0          79m   10.129.2.12   ip-10-0-16-104.us-east-2.compute.internal   <none>           <none>
io-app-78c4f8b784-5x9bw   1/1     Running   0          79m   10.128.2.20   ip-10-0-78-34.us-east-2.compute.internal    <none>           <none>
io-app-78c4f8b784-jl8np   1/1     Running   0          79m   10.131.0.23   ip-10-0-50-78.us-east-2.compute.internal    <none>           <none>
```

https://github.com/kadalu/kadalu/assets/37169113/4a423dc8-b655-404b-a96f-23410e9af0ba

Closing thoughts:
1. We would've received more reports if the core tech, ie, replication isn't working as expected, still I don't write off your bug and at the same time, unless I see it I can't believe
2. Your bug report is missing KadaluStorageCR, might be you are using path mode 🤔?
3. Anyways, I can relook if you can provide a coded reproducer image which I could just deploy.
