### ISSUE TITLE
[Need Help]:  Expect shared path for different pods across machine/nodes

### ISSUE THREAD

**Issue by liyuntao** [kadalu/kadalu#1029]
Hey guys, I am trying to adopt kadalu with my existing External glusterFS server.

```yaml
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: pv-ext
spec:
  type: External
  single_pv_per_pool: true             # Also tried false either. not working
  details:
    gluster_hosts:
      - my-gluster-ip        
    gluster_volname: app             
    gluster_options: log-level=DEBUG   

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-ext
spec:
  storageClassName: kadalu.pv-ext
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-ext
  labels:
    app: sample-app
spec:
  containers:
  - name: sample-app
    image: docker.io/kadalu/sample-pv-check-app:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: "/mnt/pv"
      name: csivol
  volumes:
  - name: csivol
    persistentVolumeClaim:
      claimName: pv-ext
```

The yaml is basically same as `/example` and quite simple.
The PVC is being applied to two different namespaces. Let's say it `ns-a` and `ns-b`

But when I deploy two pods with pvc claimd in same namespace, the file under volume_path cannot be seen by each other, but either file is ok during pod delete & re-created. Below is my attempts:

1. The mount point is same. e.g. '/mnt/pv'
2. create podA under `ns-a`, kubectl exec -i podA touch /mnt/pv/a.txt
3. create podB under `ns-b`, cannot find file `a.txt` under '/mnt/pv'.
4. create file `b.txt` in podB.  Also, the file could not be seen inside podA. It seems isolated under two different paths inside actual glusterFs volume.

Can anybody help me with it?
