### ISSUE TITLE
[Bug]: Failed to mount device - not a block device

### ISSUE THREAD

**Issue by TristisOris** [kadalu/kadalu#1042]
**Describe the bug**
NFS path can't be mounted because it not a block device.

**To Reproduce**
```
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  # This will be used as name of PV Hosting Volume
  name: storage-pool-1
spec:
  type: Replica3
  storage:
    - node: node2
      device: /mnt/test
    - node: node3
      device: /mnt/test
    - node: node4
      device: /mnt/test
    - node: node5
      device: /mnt/test
    - node: node6
      device: /mnt/test
    - node: node7
      device: /mnt/test
```

**Environment:**
kubectl kadalu version
kubectl-kadalu plugin: 1.2.0
kadalu pod(s) versions
pod/kadalu-csi-nodeplugin-8bxc4: 1.2.0
pod/kadalu-csi-nodeplugin-gl2r7: 1.2.0
pod/kadalu-csi-nodeplugin-gwvml: 1.2.0
pod/kadalu-csi-nodeplugin-qsj5g: 1.2.0
pod/kadalu-csi-nodeplugin-r4rxr: 1.2.0
pod/kadalu-csi-nodeplugin-tcc8v: 1.2.0
pod/kadalu-csi-nodeplugin-vmtnw: 1.2.0
pod/kadalu-csi-provisioner-0: 1.2.0
pod/operator-58ddcb697c-gdcc4: 1.2.0
Error while running the following command
$ kubectl exec -nkadalu pod/server-storage-pool-1-0-0 -- bash -c echo $KADALU_VERSION

error: unable to upgrade connection: container not found ("server")

**Screenshots or Logs**
server-storage-pool-1-5-0:
```
[2024-01-26 07:38:49,931] INFO [glusterfsd - 129:create_and_mount_brick] - Failed to mount device, continuing with mkfs	 err=[32]  mount: /bricks/storage-pool-1/data: /brickdev/test is not a block device. fstype=xfs device=/brickdev/test mountdir=/bricks/storage-pool-1/data
[2024-01-26 07:38:49,931] ERROR [glusterfsd - 181:create_and_mount_brick] - Failed to mount export brick	 fstype=xfs device=/brickdev/test mountdir=/bricks/storage-pool-1/data error=[32]  mount: /bricks/storage-pool-1/data: /brickdev/test is not a block device.
```
Environment:
```
BRICK_DEVICE : /mnt/test
BRICK_INDEX : 5
BRICK_PATH : /bricks/storage-pool-1/data/brick
HOSTNAME : node7
K8S_DIST : kubernetes
KADALU_VERSION : 1.2.0
NODEID : node-5
SHD_REQUIRED : 1
SUBVOL_ROOT : subvol
VERBOSE : no
VOLUME : storage-pool-1
VOLUME_ID : 5f796784-bc1b-11ee-a19d-ae3c1976d0e5
VOLUME_TYPE : Replica3
```
Mounts
```
/dev
from gluster-dev (rw)
/sys/fs/cgroup
from gluster-cgroup (ro)
/lib/modules
from gluster-kmods (ro)
/var/lib/gluster
from glusterfsd-volfilesdir (rw)
/bricks/storage-pool-1
from glusterfsd-mountdir (rw)
/brickdev
from brick-device-dir (rw)
/var/run/secrets/kubernetes.io/serviceaccount
from kube-api-access-r5pvl (ro)
```
