### ISSUE TITLE
[Bug]: Storage not created

### ISSUE THREAD

**Issue by TristisOris** [kadalu/kadalu#1044]
**Describe the bug**
```
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage-pool-1
spec:
  type: Replica3
  storage:
    - node: node3
      path: /mnt/test
    - node: node4
      path: /mnt/test
    - node: node5
      path: /mnt/test
```
after apply this config, pods are created, but not storage. So at next step pv can't allocate any space.

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv1
spec:
  storageClassName: kadalu.storage-pool-1
  accessModes:
    - ReadWriteMany # ReadWriteOnce ReadWriteMany
  resources:
    requests:
      storage: 10Gi
```

`storageclass.storage.k8s.io "kadalu.storage-pool-1" not found`

**Environment:**
kubectl kadalu version
kubectl-kadalu plugin: 1.2.0
kadalu pod(s) versions
pod/kadalu-csi-nodeplugin-65xpp: 1.2.0
pod/kadalu-csi-nodeplugin-87sgg: 1.2.0
pod/kadalu-csi-nodeplugin-fhbxn: 1.2.0
pod/kadalu-csi-nodeplugin-hzpjc: 1.2.0
pod/kadalu-csi-nodeplugin-p9bv9: 1.2.0
pod/kadalu-csi-nodeplugin-qhpvp: 1.2.0
pod/kadalu-csi-nodeplugin-wnm94: 1.2.0
pod/kadalu-csi-provisioner-0: 1.2.0
pod/operator-58ddcb697c-4hh84: 1.2.0
pod/server-storage-pool-1-0-0: 1.2.0
pod/server-storage-pool-1-1-0: 1.2.0
pod/server-storage-pool-1-2-0: 1.2.0

**Screenshots or Logs**
![изображение](https://github.com/kadalu/kadalu/assets/1270117/e46fe82b-c595-4888-ad0c-201759bd0f85)
![изображение](https://github.com/kadalu/kadalu/assets/1270117/3727062d-e88c-4214-bad9-bee2320803c1)
