### ISSUE TITLE
Kadalu and external glusterfs

### ISSUE THREAD

**Issue by yatakoi** [kadalu/kadalu#1093]
To test `kadalu`, I installed Kubernetes via `kind`. Separately, on a virtual machine, I installed `glusterfs`.

On a virtual machine glusterfs
```
mkdir -p /data/gfs_volume/
mkfs.xfs /dev/vdb
mount /dev/vdb /data/gfs_volume
gluster volume create gv0   max:/data/gfs_volume/brick
gluster volume start gv0
```

In kubernetes
```
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: gluster
spec:
  type: External
  # Omitting 'single_pv_per_pool' or using 'false' as a value will create
  # 1 PV : 1 Subdir in external gluster volume
  single_pv_per_pool: false
  details:
    # gluster_hosts: [ gluster1.kadalu.io, gluster2.kadalu.io ]
    gluster_host: 10.10.100.101
    gluster_volname: gv0
    gluster_options: log-level=DEBUG
```

But storageClass was not created
```
max@max:~$ kubectl get sc
NAME                 PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
standard (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  38m
```

I started looking in the documentation on how to correctly create a storageClass, but I didn't find it specifically in the version for working with external glustefs. I looked here https://docs.kadalu.tech/k8s-storage/latest/external-gluster-storage/

Could you tell me how to create a working storageClass?
