### ISSUE TITLE
[Bug]: Is it allowed to connect to the external glusterfs using TLS method?

### ISSUE THREAD

**Issue by shoufuzhang** [kadalu/kadalu#1098]
**Is your feature request related to a problem? Please describe.**
I need to connect to an external glusterfs using TLS. I'm not sure how to set up kadalu to enable it to access glusterfs using the TLS protocol.

**Verification steps**
1. glusterfs volume start tls
```
[root@rhb-test-middleware glusterfs]# gluster volume  get gl-data-zsf client.ssl
Option                                   Value
------                                   -----
client.ssl                               on
[root@rhb-test-middleware glusterfs]# gluster volume  get gl-data-zsf server.ssl
Option                                   Value
------                                   -----
server.ssl                               on
```

2. I can correctly mount the volume on the VM, and I am using tls.
```bash
[2025-04-22 09:09:05.495234 +0000] I [MSGID: 100030] [glusterfsd.c:2767:main] 0-/usr/sbin/glusterfs: Started running version [{arg=/usr/sbin/glusterfs}, {version=10.5}, {cmdlinestr=/usr/sbin/glusterfs --process-name fuse --volfile-server=10.1.2.5 --volfile-id=gl-data-zsf /mnt}]
[2025-04-22 09:09:05.496782 +0000] I [glusterfsd.c:2447:daemonize] 0-glusterfs: Pid of current running process is 2208454
[2025-04-22 09:09:05.498584 +0000] E [MSGID: 101242] [gf-io-uring.c:410:gf_io_uring_setup] 0-io: io_uring_setup() failed. [Operation not permitted]
[2025-04-22 09:09:05.501708 +0000] I [socket.c:4288:ssl_setup_connection_params] 0-glusterfs: SSL support for MGMT is ENABLED IO path is ENABLED certificate depth is 1 for peer
[2025-04-22 09:09:05.508223 +0000] I [MSGID: 101190] [event-epoll.c:667:event_dispatch_epoll_worker] 0-epoll: Started thread with index [{index=0}]
[2025-04-22 09:09:05.508267 +0000] I [MSGID: 101190] [event-epoll.c:667:event_dispatch_epoll_worker] 0-epoll: Started thread with index [{index=1}]
[2025-04-22 09:09:05.531130 +0000] I [io-stats.c:3711:ios_sample_buf_size_configure] 0-gl-data-zsf: Configure ios_sample_buf  size is 1024 because ios_sample_interval is 0
[2025-04-22 09:09:05.531608 +0000] I [socket.c:4288:ssl_setup_connection_params] 0-gl-data-zsf-client-0: SSL support for MGMT is ENABLED IO path is ENABLED certificate depth is 1 for peer
[2025-04-22 09:09:05.533338 +0000] I [MSGID: 114020] [client.c:2336:notify] 0-gl-data-zsf-client-0: parent translators are ready, attempting connect on transport []
Final graph:
+------------------------------------------------------------------------------+
  1: volume gl-data-zsf-client-0
  2:     type protocol/client
  3:     option ping-timeout 42
  4:     option remote-host 10.1.2.5
  5:     option remote-subvolume /data/glfs/zsf
  6:     option transport-type socket
  7:     option transport.address-family inet
  8:     option transport.socket.ssl-enabled on
  9:     option transport.tcp-user-timeout 0
 10:     option transport.socket.keepalive-time 20
 11:     option transport.socket.keepalive-interval 2
 12:     option transport.socket.keepalive-count 9
 13:     option strict-locks off
 14:     option send-gids true
 15: end-volume
 16:
 17: volume gl-data-zsf-dht
 18:     type cluster/distribute
 19:     option lock-migration off
 20:     option force-migration off
 21:     subvolumes gl-data-zsf-client-0
 22: end-volume
 23:
 24: volume gl-data-zsf-write-behind
 25:     type performance/write-behind
 26:     subvolumes gl-data-zsf-dht
 27: end-volume
 28:
 29: volume gl-data-zsf-open-behind
 30:     type performance/open-behind
 31:     subvolumes gl-data-zsf-write-behind
 32: end-volume
 33:
 34: volume gl-data-zsf-quick-read
 35:     type performance/quick-read
 36:     subvolumes gl-data-zsf-open-behind
 37: end-volume
 38:
 39: volume gl-data-zsf-md-cache
 40:     type performance/md-cache
 41:     subvolumes gl-data-zsf-quick-read
 42: end-volume
 43:
 44: volume gl-data-zsf-io-threads
 45:     type performance/io-threads
 46:     subvolumes gl-data-zsf-md-cache
 47: end-volume
 48:
 49: volume gl-data-zsf
 50:     type debug/io-stats
 51:     option log-level INFO
 52:     option threads 16
 53:     option latency-measurement off
 54:     option count-fop-hits off
 55:     option global-threading off
 56:     subvolumes gl-data-zsf-io-threads
 57: end-volume
 58:
 59: volume meta-autoload
 60:     type meta
 61:     subvolumes gl-data-zsf
 62: end-volume
 63:
+------------------------------------------------------------------------------+
[2025-04-22 09:09:05.558851 +0000] I [rpc-clnt.c:1973:rpc_clnt_reconfig] 0-gl-data-zsf-client-0: changing port to 53546 (from 0)
[2025-04-22 09:09:05.559019 +0000] I [socket.c:833:__socket_shutdown] 0-gl-data-zsf-client-0: intentional socket shutdown(12)
[2025-04-22 09:09:05.561743 +0000] I [socket.c:4288:ssl_setup_connection_params] 0-gl-data-zsf-client-0: SSL support for MGMT is ENABLED IO path is ENABLED certificate depth is 1 for peer 10.1.2.5:24007
[2025-04-22 09:09:05.582386 +0000] I [MSGID: 114057] [client-handshake.c:1118:select_server_supported_programs] 0-gl-data-zsf-client-0: Using Program [{Program-name=GlusterFS 4.x v1}, {Num=1298437}, {Version=400}]
[2025-04-22 09:09:05.584921 +0000] I [MSGID: 114046] [client-handshake.c:856:client_setvolume_cbk] 0-gl-data-zsf-client-0: Connected, attached to remote volume [{conn-name=gl-data-zsf-client-0}, {remote_subvol=/data/glfs/zsf}]
[2025-04-22 09:09:05.586510 +0000] I [fuse-bridge.c:5294:fuse_init] 0-glusterfs-fuse: FUSE inited with protocol versions: glusterfs 7.24 kernel 7.36
[2025-04-22 09:09:05.586531 +0000] I [fuse-bridge.c:5926:fuse_graph_sync] 0-fuse: switched to graph 0
```
3. I now install kadalu via the following command
```bash
kubectl apply -f https://github.com/kadalu/kadalu/releases/latest/download/kadalu-operator.yaml
```
4. Use the following yaml to create a storageClass and pv and pod
```yaml
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: zsf-llmser-pv # Keep changing the name for different volumes
spec:
  type: External
  single_pv_per_pool: true             # Will map 1 Gluster Volume : 1 PV
  details:
    gluster_hosts:
      - 10.1.2.5             # Change to your gluster host
    gluster_volname: gl-data-zsf
    gluster_options: log-level=DEBUG   # Comma separated options

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zsf-llmser-pvc
spec:
  storageClassName: kadalu.zsf-llmser-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zsf-mobile-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zsf-mobile-website
  template:
    metadata:
      labels:
        app: zsf-mobile-website
    spec:
      nodeSelector:
        kubernetes.io/hostname: "rhb-test-k8s-m01"
      containers:
      - name: zsf-mobile-website
        image: registry.cn-zhangjiakou.aliyuncs.com/wiz-en-image/mobile-website:1.33.7.b69
        resources:
          limits:
            memory: 1Gi
        env:
        - name: aliyun_logs_mobile-website
          value: stdout
        ports:
        - name: http
          containerPort: 80
        volumeMounts: # 本地存储路径
        - name: iamser-log
          mountPath: /log
      volumes: # 声明pvc
      - name: iamser-log
        persistentVolumeClaim:
         claimName: zsf-llmser-pvc
      imagePullSecrets:
      - name: wiz-dev-auth
```
5. Pvc will be in a pending state, and I will prompt for an error in the glusterfs.
```bash
[2025-04-22 08:54:46.756860 +0000] E [socket.c:224:ssl_dump_error_stack] 0-socket.management:   error:0A000126:SSL routines::unexpected eof while reading
[2025-04-22 08:54:48.767368 +0000] I [socket.c:4288:ssl_setup_connection_params] 0-socket.management: SSL support for MGMT is ENABLED IO path is ENABLED certificate depth is 1 for peer 10.1.2.8:32580
```

Please guide me how to configure the connection glusterfs using TLS
