### ISSUE TITLE
Indentation was not proper in storage-config.yaml . The log file did not throw any error, even though the error exist in config-file 

### ISSUE THREAD

**Issue by manvantarah** [kadalu/kadalu#135]
### kubectl logs -f -n kadalu operator-68649f4bb6-49hv2

+ pid=0
+ cmd=/usr/bin/python3
+ script=/kadalu/main.py
+ trap 'kill ${!}; term_handler' SIGTERM
+ pid=7
+ true
+ wait 8
+ tail -f /dev/null
+ /usr/bin/python3 /kadalu/main.py
[2020-01-17 07:31:54,301] DEBUG [rest - 219:request] - response body: {"kind":"ConfigMapList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/namespaces/kadalu/configmaps","resourceVersion":"102776"},"items":[]}

[2020-01-17 07:32:11,452] INFO [main - 445:deploy_storage_class] - Deployed StorageClass	 manifest=/kadalu/templates/storageclass.yaml

**Comment by aravindavk** [comment]
Please paste the content of storage-config.yaml file used

**Comment by manvantarah** [comment]
# File: storage-config.yaml
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
    # This will be used as name of PV Hosting Volume
    name: storage-pool-1
    spec:
    type: Replica1
    storage:
      - node: minikube      # node name as shown in `kubectl get nodes`
        device: /root/disk  # Device to provide storage to all PVs

**Comment by manvantarah** [comment]
@aravindavk - Bad indentation storage-config.yaml

**Comment by manvantarah** [comment]
# File: storage-config.yaml
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
    # This will be used as name of PV Hosting Volume
    name: storage-pool-1
spec:
    type: Replica1
    storage:
      - node: minikube      # node name as shown in `kubectl get nodes`
        device: /root/disk  # Device to provide storage to all PVs

**Comment by manvantarah** [comment]
@aravindavk - Proper indentation storage-file.yaml

**Comment by manvantarah** [comment]
```
# File: storage-config.yaml
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
    # This will be used as name of PV Hosting Volume
    name: storage-pool-1
  spec:
      type: Replica1
      storage:
       - node: minikube      # node name as shown in `kubectl get nodes`
          device: /root/disk  # Device to provide storage to all PVs
```
