### ISSUE TITLE
Cannot provision volume after cleanup & reinstall - RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins_registry/kadalu/csi.sock

### ISSUE THREAD

**Issue by superbiche** [kadalu/kadalu#149]
I've installed Kadalu then reset my K8S 1.17 cluster, etcd, cleaned everything and started again.

Then I removed Kadalu, ran the cleanup script, re-deployed it and the 2 replica3 clusters, but I get this error in kubelet journal: 
```
janv. 25 00:29:10 medusa.tld.eu kubelet[9403]: E0125 00:29:10.407510    9403 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins_registry/kadalu/csi.sock" failed. No retries permitted until 2020-01-25 00:31:12.407435007 +0100 CET m=+7494.659840144 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins_registry/kadalu/csi.sock, err: rpc error: code = Unimplemented desc = Method not found!"
```
---
EDIT: manifests attached

```yaml
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage-masters-1
spec:
  type: Replica3
  storage:
    - node: marina.tld.eu
      device: /dev/nvme0n1p3
    - node: medusa.tld.eu
      device: /dev/nvme0n1p3
    - node: roadtrip.tld.eu
      device: /dev/nvme0n1p3
```
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: cc-media
    namespace: us-staging-nosync
spec:
    storageClassName: kadalu.replica3
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 1Gi
```

Worked perfectly on the same Kubernetes version like a day ago, and I have no idea if this error happened at that moment - my journal was flooded by network issues, hence the cluster flush.
Now network works perfectly so I don't think it's related.

Do you know what may be happening? Thanks
