### ISSUE TITLE
flexibility of kadalu PV hosting volume

### ISSUE THREAD

**Issue by humblec** [kadalu/kadalu#18]
At present , its an admin overhead to create PV Hosting volume. This invite a manual intervention /blocking op on the path. What about, we give a choice of submitting a PVC name in the CRD, so that we dont care where we operate ? 

```
apiVersion: kadalu-operator.gluster/v1alpha1
kind: KadaluVolume
metadata:
  # This will be used as name of PV Hosting Volume
  name: gvol1
spec:
  type: Replica1
  storage:
    - node: kube1  # node name as shown in `kubectl get nodes`
      path: /mnt/data  # Directory path xattrs support.
  options: {}
```
@amarts thoughts here ?

**Comment by amarts** [comment]
Thanks for the points @humblec. Ack on not doing manual overheads.

**Comment by aravindavk** [comment]
This is definitely possible. The only requirement is that PV should support xattrs and option to enable project Quota while mounting that volume.

1. Claim for local volume or EBS volume
2. Use that claim name in KadaluStorage CRD

```
apiVersion: kadalu-operator.gluster/v1alpha1
kind: KadaluStorage
metadata:
  # This will be used as name of PV Hosting Volume
  name: storage-pool-1
spec:
  type: Replica1
  storage:
    - storage-claim-0
  options: {}
```

For Replica 3 volume,

```
apiVersion: kadalu-operator.gluster/v1alpha1
kind: KadaluStorage
metadata:
  # This will be used as name of PV Hosting Volume
  name: storage-pool-2
spec:
  type: Replica3
  storage:
    - storage-claim-1
    - storage-claim-2
    - storage-claim-3
  options: {}
```
