### ISSUE TITLE
problem running elasticsearch cluster on replica3

### ISSUE THREAD

**Issue by davehatton** [kadalu/kadalu#287]
I have an elasticsearch cluster deployed from a statefulset  that is working when using heketi/gluster but fails to start when migrated to kadalu/replica3 storage.

The key message from the application appears to be 

```
2020-08-25T08:46:10.799184289Z java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
2020-08-25T08:46:10.799197336Z Likely root cause: java.io.IOException: Value too large for defined data type
```

My storage is presented using 

```
---
 kind: KadaluStorage
 apiVersion: kadalu-operator.storage/v1alpha1
 metadata:
   name: storage-pool-1
 spec:
   type: Replica3
   storage:
   - node: k807
     device: /dev/sdb
   - node: k808
     device: /dev/sdb
   - node: k809
     device: /dev/sdb

...
```

and my stateful set is:

```
---
 apiVersion: apps/v1
 kind: StatefulSet
 metadata:
   namespace: monitoring
   name: es-cluster
 spec:
   serviceName: elasticsearch
   replicas: 3
   selector:
     matchLabels:
       app: elasticsearch
   template:
     metadata:
       labels:
         app: elasticsearch
     spec:
       containers:
       - name: elasticsearch
         image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
         resources:
           limits:
             cpu: 1000m
           requests:
             cpu: 100m
         ports:
         - containerPort: 9200
           name: rest
           protocol: TCP
         - containerPort: 9300
           name: inter-node
           protocol: TCP
         volumeMounts:
         - name: data
           mountPath: /usr/share/elasticsearch/data
         env:
           - name: cluster.name
             value: k8s-logs
           - name: node.name
             valueFrom:
               fieldRef:
                 fieldPath: metadata.name
           - name: discovery.seed_hosts
             value: "es-cluster-0.elasticsearch,es-cluster-1.elasticsearch,es-cluster-2.elasticsearch"
           - name: cluster.initial_master_nodes
             value: "es-cluster-0,es-cluster-1,es-cluster-2"
           - name: ES_JAVA_OPTS
             value: "-Xms512m -Xmx512m"
       initContainers:
       - name: fix-permissions
         image: busybox
         command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
         securityContext:
           privileged: true
         volumeMounts:
         - name: data
           mountPath: /usr/share/elasticsearch/data
       - name: increase-vm-max-map
         image: busybox
         command: ["sysctl", "-w", "vm.max_map_count=262144"]
         securityContext:
           privileged: true
       - name: increase-fd-ulimit
         image: busybox
         command: ["sh", "-c", "ulimit -n 65536"]
         securityContext:
           privileged: true
   volumeClaimTemplates:
   - metadata:
       name: data
       labels:
         app: elasticsearch
     spec:
       accessModes:
       -  ReadWriteMany
       storageClassName: kadalu.replica3
       resources:
         requests:
           storage: 10Gi

...
```

Any suggestions on what maybe wrong?

**Comment by amarts** [comment]
Thanks for the yml in my setup, when I changed `kadalu.replica3` to `kadalu.replica1`, I found no issues.


```
root@bulde:/home/amar/work/kadalu/kadalu# kubectl get pvc
NAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
data-es-cluster-0   Bound    pvc-0eb03fc7-3419-438e-8235-0bdcbe4e2a1d   1Gi        RWX            kadalu.replica1   4m
data-es-cluster-1   Bound    pvc-5317653a-b7e6-4879-aa61-d617260fff56   1Gi        RWX            kadalu.replica1   118s
data-es-cluster-2   Bound    pvc-31389fc4-7427-43e8-bd61-f42255188f8c   1Gi        RWX            kadalu.replica1   93s
root@bulde:/home/amar/work/kadalu/kadalu# kubectl get pods -owide
NAME           READY   STATUS    RESTARTS   AGE    IP            NODE              NOMINATED NODE   READINESS GATES
es-cluster-0   1/1     Running   0          3m7s   172.17.0.8    bulde.kadalu.io   <none>           <none>
es-cluster-1   1/1     Running   0          65s    172.17.0.9    bulde.kadalu.io   <none>           <none>
es-cluster-2   1/1     Running   0          40s    172.17.0.10   bulde.kadalu.io   <none>           <none>
```

Testing further with kadalu.replica3. Meantime, I wanted to check if your application nodes have any firewall etc? We need port 24007 to be open for glusterfs processes.

**Comment by xinghui-hou** [comment]
### same question
1. use kadalu.replica3 
![image](https://user-images.githubusercontent.com/10824788/97129812-c98f6900-177a-11eb-9f12-e16983b4989a.png)


2. Some index red
red    open ilm-history-1-000002            ZTBP-AOGS42iv_RcG30m9Q 1 1

3.maybe is a glusterfs bug
https://github.com/gluster/glusterfs/issues/631

**Comment by xangxiong** [comment]
Not 100% sure if this is related, but with my test setup, using Replica1, Replica2, and Replica3 with ReadWriteMany enabled, I get "Value too large for defined data type" whenever I execute the flock command on the volume mounted.  Linux command to test flock is:

cd /tmp
echo "test" > /tmp/test.txt
exec 100>/tmp/test.txt || exit 1
flock 100 || exit 1

This is assuming /tmp is mounted from a PersistentVolume generated by GlusterFS/Kadalu.  I've tested this on Kadalu 0.7.7 using the operater definition https://github.com/kadalu/kadalu/blob/0.7.7/manifests/kadalu-operator.yaml

**Comment by aravindavk** [comment]
> This is assuming /tmp is mounted from a PersistentVolume generated by GlusterFS/Kadalu. I've tested this on Kadalu 0.7.7 using the operater definition https://github.com/kadalu/kadalu/blob/0.7.7/manifests/kadalu-operator.yaml

Please share the PVC yaml used so that we can confirm if `/tmp` is mounted from Kadalu.

**Comment by xangxiong** [comment]
Hi aravindavk,

The PVC yaml output from Kubernetes is below.  From trying to reproduce this, I realize that I used the kadalu-operator.yaml for 0.7.5 previously, but to test 0.7.7, I updated the version # to 0.7.7.  So I re-ran the test with just 0.7.5 since I'm testing against Kubernetes 1.15 which does not have `apiextensions.k8s.io/v1` yet.  I also included the commands I use (`test_kadalu.txt` below) to test and configure the Kadalu deployment in case that helps identify any issues that may be related just to how I configured/deployed Kadalu.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kadalu
  creationTimestamp: "2021-02-23T16:40:09Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: test-kadalu-pvc
  name: test-kadalu-pvc-test-kadalu-pvc-0
  namespace: kadalu
  resourceVersion: "9928"
  selfLink: /api/v1/namespaces/kadalu/persistentvolumeclaims/test-kadalu-pvc-test-kadalu-pvc-0
  uid: 3cfa14d3-9dd8-4e00-8855-9e919c3559b7
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: kadalu-storage
  volumeMode: Filesystem
  volumeName: pvc-3cfa14d3-9dd8-4e00-8855-9e919c3559b7
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Mi
  phase: Bound
```

[test_kadalu.txt](https://github.com/kadalu/kadalu/files/6030497/test_kadalu.txt)

**Comment by amarts** [comment]
With release of 0.8.6, we are now supporting virtblock device as mount, which means, the Database workloads should smoothly run on top of kadalu.

More on it @ https://github.com/kadalu/kadalu/blob/devel/doc/storage-classes.adoc#pv_type

**Comment by gnossen** [comment]
@amarts I believe I'm still seeing this issue on `0.8.6` with `pv_type: Block`. I've gotten it down to a minimal reproduction:

```yaml
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: single1
spec:
  type: Replica1
  pvReclaimPolicy: archive
  volume_id: e106fc30-c641-11eb-90c8-8a115b683253
  storage:
    - node: node7
      device: /dev/sda1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kadalu.db-single1
provisioner: kadalu
parameters:
  storage_name: "single1"
  pv_type: Block
```

```C
#include <stdio.h>
#include <fcntl.h>
#include <libgen.h>
#include <unistd.h>
#include <string.h>
#include <sys/stat.h>
#include <errno.h>
#include <stdlib.h>

#define RETURN_IF_ERROR(expr) \
    do { \
        int err = (expr); \
        if (err == -1) { \
            fprintf(stderr, "Error calling "  #expr " : %s\n", strerror(errno)); \
            return 1; \
        } \
    } while(0);

int main(int argc, char ** argv) {
    if (argc != 2) {
        fprintf(stderr, "USAGE: %s FILEPATH\n", argv[0]);
        return 1;
    }

    char* filepath = argv[1];
    int fd = openat(AT_FDCWD, filepath, O_RDWR | O_CREAT | O_NOFOLLOW | O_CLOEXEC, 0644);

    struct flock flck = {
        .l_type = F_RDLCK,
        .l_whence = SEEK_SET,
        .l_start = 0,
        .l_len = 1,
    };
    RETURN_IF_ERROR(fcntl(fd, F_SETLK, &flck))
    printf("Success.\n");
    return 0;
}
```

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluster-setlk-repro
  labels:
    app: gluster-setlk-repro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluster-setlk-repro
  template:
    metadata:
      labels:
        app: gluster-setlk-repro
    spec:
      containers:
      - name: gluster-setlk-repro
        image: docker:5000/gluster-setlk-repro:6
        args:
          - /repro
          - /mnt/data/test.db
        volumeMounts:
        - mountPath: "/mnt/data"
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gluster-setlk-repro-pv2
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gluster-setlk-repro-pv2
spec:
  storageClassName: kadalu.db-single1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

This produces the following output:

```
Error calling fcntl(fd, F_SETLK, &flck) : Value too large for data type
```

When running this repro under `strace`, I get the following (pretty nonsensical) output:

```
[pid   405] fcntl(3, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=0, l_len=1}) = -1 EOVERFLOW (Value too large for defined data type)
```

I believe this is the same as the `java.io.IOException: Value too large for defined data type` mentioned in the original post in this thread. I get the same result whether I use a `storageClass` with `pv_type: Block` or not.

*Edit: I've run this repro with both glibc and musl libc. Same result. I cannot reproduce locally with gluster, so I think this is likely to be a problem in one of the kadalu xlators.*
