### ISSUE TITLE
Configuring tolerations (espacially for server & nodeplugin)

### ISSUE THREAD

**Issue by tsufeki** [kadalu/kadalu#302]
It seems there's no way to configure tolerations for kadalu pods, which makes kadalu unusable in scenarios with "special use" tainted nodes:

* having dedicated "storage" nodes (server pods won't start)
* other "special" nodes where pods need to attach kadalu volumes (no nodeplugin pods there)

Also, it may be useful to define tolerations & node affinity for other pods (e.g. csi-provisioner).

Please consider adding a configuration option for tolerations.

Thanks

**Comment by aravindavk** [comment]
Please provide more details about the use case. Why node affinity is required for csi-provisioner other pods.

Server pods do require node affinity since these services are dependent on the disk.

> other "special" nodes where pods need to attach kadalu volumes (no nodeplugin pods there)

By default, one nodeplugin pod will be present on each node. Please let us know the details about the deployment.

**Comment by tsufeki** [comment]
@aravindavk 

> By default, one nodeplugin pod will be present on each node. Please let us know the details about the deployment.

nodeplugin, like all DaemonSets respects node taints: pods won't start on a tainted node unless it has appropriate toleration.

Use case for taints is allowing keeping dedicated nodes for specific workloads (for example requiring GPU or separating CI jobs from other pods,  [see official docs](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#example-use-cases)) - and those workloads may need access to kadalu storage. My particular case is cluster of raspberry pis with amd64 master - master also handles storage (so I need `node-role.kubernetes.io/master=true` toleration on kadalu server) and some pods which can't run on arm (they attach PVs, so I need the same toleration on nodeplugin).

csi-provisioner affinity is less important (to me), but I can imagine some scenarios where one would want control scheduling of cluster infra pods with taints.

In general taints and node affinity are often necessary when managing non-homogenouos clusters.

Thanks

**Comment by amarts** [comment]
@tsufeki is it possible to provide some sample options you would like to pass to CSI specs?

**Comment by tsufeki** [comment]
@amarts Does this help? I'm not sure I understood what you ask for...
 
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kadalu-csi-nodeplugin
  namespace: kadalu
  ...
spec:
  ...
  template:
    ...
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
...
```

and same thing for server and maybe provisioner. Some other projects just read this whole from env var in operator pod (but I don't know if this would work in kadalu):

```yaml
env:
  - name: DISCOVER_TOLERATIONS
    value: |
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
```

As for affinity (only makes sense on csi-provisioner), maybe something like that:

```yaml
spec:
  ...
  template:
    ...
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - node-role.kubernetes.io/master
```
