### ISSUE TITLE
Volume mount fails in pod (rancher 2.5.1)

### ISSUE THREAD

**Issue by slash1387** [kadalu/kadalu#320]
hi all
we have successfully installed kadalu with external glusterfs storage class. pvc's get created perfectly and visible in k8s, but attaching pvc to pod fails. we are using rancher 2.5.1 with custom cluster k8s 1.19.2.

![image](https://user-images.githubusercontent.com/66519368/96041365-ff277e80-0e6b-11eb-92f7-000d21126641.png)
```
kubectlnew get pods -n kadalu
NAME                          READY   STATUS    RESTARTS   AGE
kadalu-csi-nodeplugin-p49fb   3/3     Running   3          90m
kadalu-csi-nodeplugin-xh6lr   3/3     Running   3          90m
kadalu-csi-provisioner-0      4/4     Running   4          90m
operator-74c9fb55c4-zbnkd     1/1     Running   1          92m
```
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-kadalu
spec:
  # Add 'kadalu.external.' to name from KadaluStorage kind
  storageClassName: kadalu.external.ext-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # This needs to be set using 'kadalu-quotad'
      storage: 500Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: sample-app
spec:
  containers:
  - name: sample-app
    image: docker.io/kadalu/sample-pv-check-app:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: "/mnt/pv"
      name: csivol
  volumes:
  - name: csivol
    persistentVolumeClaim:
      claimName: pvc-kadalu
  restartPolicy: OnFailure

```
