### ISSUE TITLE
Helm Chart feedbacks to improve further!

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#398]
Honest feedback from well-wisher / user @joejulian

> Just gave it a look. This is really confusing since it's done in python. There's no API definition to read and the CRDs are incomplete. Since you're using a helm3 (v2 api) chart, CRDs should be in the crds/ directory. This will allow you to use chart templating to create resources that use that definition. If you include the CRD in templates/, any resources you might want to create that uses that CRD will fail because the resource is not defined in the apiserver at the time of validation. (I'd offer a PR, but it will take a significant amount of time to work out the correct CRD definition by walking how it's used in the code).
> 
> I don't see, from the helm chart, that kudo would be of any value. Looks declarative to me. :D
> 
> Since you're not using go and you have no structs with which to generate the CRD, you might want to at least have one single source of truth that is used everywhere. Currently, you have the CRD defined in 4 (iirc) places and none of them are the same (could have a make target to copy from the source to the places it's needed).
> 
> If you define the API, I might see about opening a PR to write it up in go so you can use controller-gen to, at least, maintain the CRD.

**Comment by amarts** [comment]
Plan is, in next 2 months we will properly 'define' the CRD with documents, so the values can be properly passed in helm chart, which also can be further optimized with kudo charts.

**Comment by amarts** [comment]
CRD definition now changed to v1 from v1beta1 through #413

```yaml
---
...
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string # valid options are 'External', 'Replica{1,2,3}'
                storage:
                  type: array
                  items:
                    type: object
                    properties:
                      node:
                        type: string
                      device:
                        type: string
                      path:
                        type: string
                      pvc:
                        type: string
                tiebreaker:
                  type: object
                  properties:
                    deployment:
                      type: string
                    node:
                      type: string
                    path:
                      type: string
                    port:
                      type: integer
                details:
                  type: object
                  properties:
                    gluster_host:
                      type: string
                    gluster_hosts:
                      type: array
                      items:
                        type: string
                    gluster_volname:
                      type: string
                    gluster_options:
                      type: string
```
