### ISSUE TITLE
Docs for external GlusterFS storage are outdated

### ISSUE THREAD

**Issue by robojones** [kadalu/kadalu#417]
The latest version introduced incompatible changes to the schema for the external GlusterFS storage configuration.
The changes were made in #413 and are **not documented**.

The [kubectl Kadalu Plugin](https://pypi.org/project/kubectl-kadalu/) version 0.7.0 (latest version on pip), which I have installed on my server, returned a schema validation error when I tried to add external GlusterFS storage in a cluster. The cluster was newly created, running the latest version of Kadalu.

Both, the corresponding [RFC page](https://kadalu.io/rfcs/0001-external-gluster-storage.html) and the [docs page](https://kadalu.io/docs/k8s-storage/latest/external-gluster-storage) show **different** YAML examples but **none of them work** with the latest schema and implementation.

The previous model looked like this:
```yaml
# File: storage-config.yaml
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  # This will be used as name of PV Hosting Volume
  name: ext-storage
spec:
  type: External # Here, volume type can be anything
  details:
    - gluster_node: node1
      gluster_volname: volume_name # Volume name
      gluster_options: log_level=DEBUG
```

It was changed to this:
```yaml
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: ext-config
spec:
  type: External
  details:
    gluster_host: gluster1.kadalu.io
    # gluster_hosts: # alternative using multiple hosts
    #   - gluster1.kadalu.io
    #   - gluster2.kadalu.io
    gluster_volname: kadalu
    gluster_options: log-level=DEBUG
```

This change is not reflected in the docs. The behavior when using the gluster_hosts property is not documented at all.
