### ISSUE TITLE
kadalu KadaluStorage can use node dir or not 

### ISSUE THREAD

**Issue by httaotao** [kadalu/kadalu#519]
hello, we used hekti to manage glusterfs volume ,but we found a serious problem with  node device which is zfs dataset.  There are many service in one device, if there are some high IO in one application, this will affect the normal operation of other services. The bottleneck is the device . 

By the way, so we want to  manage  glusterfs  volume in different node dir ,it's  better.

we want to use like this:

```
# File: storage-config.yaml
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  # This will be used as name of PV Hosting Volume
  name: storage-pool-1
spec:
  type: Replica1
  storage:
    - node: node1        # node name as shown in  glusterfs cluster.
      path:  /glusterfs
    - node: node2
      path:  /glusterfs
    - node:  node3
      path: /glusterfs

```
if we create a glusterfs volume , it can create the brick  under the path. of course , in this way, it can't use glusterfs snapshot,  we can accept.
