### ISSUE TITLE
[RFE] Use moana as a bridge between Kadalu and External Gluster Cluster

### ISSUE THREAD

**Issue by leelavg** [kadalu/kadalu#523]
I see requests from users about managing gluster volume lifecycle by Kadalu itself and our previous tracker also suggests interest in external gluster in general.

Although I didn't try external option in kadalu and [moana](https://github.com/kadalu/moana) project yet, I'm basing this RFE on my current understanding on how these components work/interact and so please take it with grain of salt.

## Moana Client and Server:
- Containerize moana server and deploy as Stateful Set backed by hostpath directory/volume if we receive `KadaluStorage` with `spec.type` as `IndependentMode`
- Embed moana cli binary in operator to talk with moana server pod for minimal CRUD operations on gluster volumes

## Moana Node:
- User has to install moana node binary and open required ports for communicating with moana server pod
- No brick operations (add/remove/replace/rebalanace) etc will not be supported on exported gluster bricks

## Configmap(s):
a. Operator discovering managed gluster storage
- To notify operator about independent(/managed) gluster storage which was already formatted and mounted on gluster hosts
- Operator will create moana server pod with necessary service endpoints and host backed storage (taking into account we can restore server state from a healthy moana node info)
``` yaml
---
# Will be supplied by user
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: external-store
spec:
  type: IndependentMode
  storage:
    - name: cluster1
    - node: gluster-host1   # External gluster node
      bricks:               # List of bricks available in gluster node
        - /bricks/brick4
        - /bricks/brick5
        - /bricks/brick6
    - node: gluster-host2
      bricks:
        - /bricks/brick4
        - /bricks/brick5
        - /bricks/brick6
    - node: gluster-host3
      bricks:
        - /bricks/brick4
        - /bricks/brick5
        - /bricks/brick6
```

b. User creates required storage classes
- moana schedules tasks for creating volumes corresponding to storage classes
- available bricks will be queried and moana creates volume on external gluster storage
``` yaml
---
# Will be supplied by user
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kadalu.ext-disperse
provisioner: kadalu
parameters:
  storage_name: external-store
  disperse-data: 4
  redundancy: 2
  mount_options: log-level=DEBUG
```
- Request similar to below will be sent to moana server pod from operator embeded moana cli for above storage class
```
kadalu volume create -c cluster1 kadalu-ext-disperse disperse-data 4 redundancy 2 gluster-host1:/bricks/brick4 gluster-host2:/bricks/brick4
gluster-host3:/bricks/brick4 gluster-host1:/bricks/brick5 gluster-host2:/bricks/brick5 gluster-host3:/bricks/brick5
```

- After volume creation we'll generate below manifest on fly to leaverage existing workflow
``` yaml
---
# Should be generated on the fly
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: ext-config
spec:
  type: External
  details:
    gluster_hosts: <from_moana_server>
    gluster_volname: <from_moana_server>
    sc_name: kadalu.ext-disperse
```

c. User requests PVC with newly created storage class
``` yaml
---
# User workflow
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv1
spec:
  storageClassName: kadalu.ext-disperse
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
```

## Unknowns (in brief):
- At the moment, above is purely a thought experiment unless we can do a POC proving the technical feasability of managaing external gluster entirely by kadalu
- Are there enough users interested in above feature or will we end up in maintaining it without any usage
- Can moana node process work without any issues in a gluster cluster managed by glusterd
- Can kadalu's fork of glusterfs be able to manage external gluster with little to nil manual effort
- If we were to prove the feasability we also need to plan for testing and release efforts ahead

## Outcomes:
- Management of external gluster volumes will be very smooth
- We can test moana on how it's going to scale with the needs
- Reach wider audience who just want to use existing gluster bricks without volume management

PS: As mentioned earlier, this is a thought experiment and any feedback is more than welcome

**Comment by aravindavk** [comment]
I feel Moana is still a few enhancements away for general availability. I will go through this tomorrow and add comments. Thanks for the details.

**Comment by aravindavk** [comment]
> Containerize moana server and deploy as Stateful Set backed by hostpath directory/volume if we receive KadaluStorage with spec.type as IndependentMode

Possible. Dockerfile is already available. That needs to be adjusted as required.

> Embed moana cli binary in operator to talk with moana server pod for minimal CRUD operations on gluster volumes

CLI is just a wrapper around ReST APIs. Currently Crystal Client is available, once the server is feature complete more client libraries will be available(Python/Node/Ruby/Go/Rust).

> Moana Node:

> User has to install moana node binary and open required ports for communicating with moana server pod

Server to node connection is not required. Only Moana nodes need access to the Server. Nodes can be behind the firewall.

> No brick operations (add/remove/replace/rebalanace) etc will not be supported on exported gluster bricks

These can be supported, Currently only "add" is implemented. Other features will be added soon.

> Configmap(s):

> a. Operator discovering managed gluster storage

Single Moana Server can manage multiple Clusters. Once nodes join a Cluster then those bricks/nodes info will be available with Moana Server. So below config file may not be required. We can mark some Clusters or Volumes as exported for Kadalu so that those will be available for use.

If the proposal is to use Config map as datastore instead of Db then It will be good to enhance Moana server itself to use ConfigMap as datastore.

> b. User creates required storage classes
> moana schedules tasks for creating volumes corresponding to storage classes
> available bricks will be queried and moana creates volume on external gluster storage

Are you thinking about creating one Gluster Volume = One PV here? Kadalu is multiplexing single Gluster Volume into multiple PVs. Intelligent Volume Provisioning is surely possible(That is Automatically provision the storage and creating the Volume based on the Size input and other meta details), but we need to decide on the approach to follow. (Ref: Feature I implemented in Glusterd2 https://github.com/gluster/glusterd2/pull/661 Warning: Very long discussion thread :))


Overall it is a good proposal. According to me the current issues related to External GlusterFS are

* Simple Quota Feature - Single GlusterFS volume is multiplexed into multiple PVs using Kadalu CSI provisioner. Simple Quota feature is used to limit the usage in each PVs. This feature is not yet available in any of the GlusterFS releases.
* To support existing Cluster - Already created Volumes using Heketi or just using Gluster CLIs. Support for managing these existing Volumes using Moana is required.
* GlusterFS client version in Kadalu CSI node pods and the GlusterFS version in externally managed storage may not be compatible.

**Approach 1**: Manage GlusterFS Volumes/Cluster externally only consume those Volumes from Kubernetes.

* From Kadalu we need to plan for a seperate GlusterFS release with Simple Quota feature enabled.
* Each exported external Volume will have one Storage Class defined.

**Approach 2**: Manage external GlusterFS Volumes from Kadalu and also consume the Volumes.

Your proposal looks mostly good, I will think about the possibility of using Config map as datastore for Moana Server instead of Db.

**Comment by leelavg** [comment]
> CLI is just a wrapper around ReST APIs. Currently Crystal Client is available, once the server is feature complete more client libraries will be available(Python/Node/Ruby/Go/Rust).

ack, we can either call the wrapper as sub-process or directly call Python bindings in operator by the time they are available.

> If the proposal is to use Config map as datastore instead of Db then It will be good to enhance Moana server itself to use ConfigMap as datastore.

yes, while creating volumes we'll be referring the configmap during runtime and figure out what bricks are available and what bricks to be used corresponding to the volume type that'll be requested in storage class. User will update the configmap if they want to add any extra nodes/bricks.

> Are you thinking about creating one Gluster Volume = One PV here? Kadalu is multiplexing single Gluster Volume into multiple PVs. Intelligent Volume Provisioning is surely possible(That is Automatically provision the storage and creating the Volume based on the Size input and other meta details), but we need to decide on the approach to follow. (Ref: Feature I implemented in Glusterd2 [gluster/glusterd2#661](https://github.com/gluster/glusterd2/pull/661) Warning: Very long discussion thread :))

I'll look into thread at the earliest. My thought process is to leverage current kadalu-format like, there'll be only one volume corresponding to the storage class (a user at most will create 6 storage classes corresponding to gluster volume types) and `pvcs` will be a subdir.

My original intention was to query `metadata.name` of user created storage class and figure out the vol type, however we can add another param `vol_type` in storage class parameters

> Overall it is a good proposal. According to me the current issues related to External GlusterFS are
> 
> * Simple Quota Feature - Single GlusterFS volume is multiplexed into multiple PVs using Kadalu CSI provisioner. Simple Quota feature is used to limit the usage in each PVs. This feature is not yet available in any of the GlusterFS releases.
> * To support existing Cluster - Already created Volumes using Heketi or just using Gluster CLIs. Support for managing these existing Volumes using Moana is required.
> * GlusterFS client version in Kadalu CSI node pods and the GlusterFS version in externally managed storage may not be compatible.

ack to all, I was also under the impression that compatibility will be the bottleneck for the implementation

> **Approach 1**: Manage GlusterFS Volumes/Cluster externally only consume those Volumes from Kubernetes.

I believe we are almost following the same and it'll be good to incrementally add moana. I guess asking user to install forked version might be a bigger hurdle.

> **Approach 2**: Manage external GlusterFS Volumes from Kadalu and also consume the Volumes.

I think we can aim for this however it calls for more contributions and may not be immediately achievable.
 
> Your proposal looks mostly good, I will think about the possibility of using Config map as datastore for Moana Server instead of Db.

ack, according to me below are the **maximum** number of config maps that we'll be using (modified a bit, can be discussed later on):

- Cluster discovery (count: 1):
``` yaml
---
# Will be supplied by user
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: external-store
spec:
  type: IndependentMode
  storage:
    cluster1:
      - node: gluster-host1   # External gluster node
        bricks:               # List of bricks available in gluster node
          - /bricks/brick4
      - node: gluster-host2
        bricks:
          - /bricks/brick4
      - node: gluster-host3
        bricks:
          - /bricks/brick4
    cluster2:
      - node: gluster-host4   # External gluster node
        bricks:               # List of bricks available in gluster node
          - /bricks/brick4
      - node: gluster-host5
        bricks:
          - /bricks/brick4
      - node: gluster-host6
        bricks:
          - /bricks/brick4     
  ```
- Storage classes (count: 6) corresponding to gluster vol types (based on available bricks and clusters):
``` yaml
---
# Will be supplied by user
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kadalu.ext
provisioner: kadalu
parameters:
  storage_name: external-store
  cluster: cluster1
  # Can be arb/dist-arb/repl/dist-repl/disp/dist-disp
  vol_type: disperse
  bricks: 6
  # Rest of params will be used in volume creation
  disperse-data: 4
  redundancy: 2
  # Mount options will be used while mounting volume to provisioner
  mount_options: log-level=DEBUG
```
- Auto-generated (correspond to volumes created in above storage class):
``` yaml 
---
# Should be generated on the fly
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: ext-config
spec:
  type: External
  details:
    gluster_hosts: <from_moana_server_based_on_sc>
    gluster_volname: <from_moana_server_based_on_sc>
    sc_name: kadalu.ext
```
- Just as a start we'll be limiting count of config maps to ( 1 + 6 + 6 )
- `sc_name` in above in yaml is what we'll be using to create subdir's for pv's (similar to kadalu.replica3, kadalu.replica2 etc)

As you have already mentioned, simple-quota and compatibility of kadalu's glusterfs fork and external cluster might be the bottleneck assuming other technical features can be implemented relatively not tougher than the compatibility.
