### ISSUE TITLE
Second external storage in cluster

### ISSUE THREAD

**Issue by pawel-detka** [kadalu/kadalu#532]
Greetings!

I have an issue with adding second storage to the cluster.

First one is defined by :

```
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage-gluster-external
spec:
  type: External
  details:
    gluster_host: gluster0.example.com 
    gluster_volname: shared_volume                     
    gluster_options: log-level=DEBUG
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-volume-gluster
spec:
  storageClassName: kadalu.external.storage-gluster-external
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
```

And it's works fine.

However when I add this:
```
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage-second-gluster-external
spec:
  type: External
  details:
    gluster_host: gluster0.second.example.com 
    gluster_volname: shared_volume 
    gluster_options: log-level=DEBUG
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-ua-volume-gluster
spec:
  storageClassName: kadalu.external.storage-second-gluster-external
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 35Gi
```

I see in  logs:

```
[2021-05-06 08:32:48,792] DEBUG [controllerserver - 37:CreateVolume] - Create Volume request     request=name: "pvc-3f5bb607-3dc2-4282-83c8-63b0646df87d"
capacity_range {
  required_bytes: 37580963840
}
volume_capabilities {
  mount {
  }
  access_mode {
    mode: MULTI_NODE_MULTI_WRITER
  }
}
parameters {
  key: "gluster_hosts"
  value: "gluster0.second.example.com "
}
parameters {
  key: "gluster_options"
  value: "log-level=DEBUG"
}
parameters {
  key: "gluster_volname"
  value: "shared_volume"
}
parameters {
  key: "hostvol_type"
  value: "External"
}
parameters {
  key: "kadalu-format"
  value: "true"
}

[2021-05-06 08:32:48,793] DEBUG [controllerserver - 56:CreateVolume] - Found PV type     pvtype=subvol capabilities=[mount {
}
access_mode {
  mode: MULTI_NODE_MULTI_WRITER
}
]
[2021-05-06 08:32:48,793] DEBUG [controllerserver - 69:CreateVolume] - Filters applied to choose storage         gluster_volname=shared_volume hostvol_type=External gluster_hosts=gluster0.second.example.com  kadalu-format=true gluster_options=log-level=DEBUG
[2021-05-06 08:32:48,794] DEBUG [controllerserver - 80:CreateVolume] - Got list of hosting Volumes       volumes=storage-gluster-external
[2021-05-06 08:32:48,799] ERROR [_server - 445:_call_behavior] - Exception calling application: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/controllerserver.py", line 109, in CreateVolume
    ext_volume = check_external_volume(request, host_volumes)
  File "/kadalu/volumeutils.py", line 916, in check_external_volume
    mount_glusterfs_with_host(hvol['g_volname'], mntdir, hvol['g_host'], hvol['g_options'])
  File "/kadalu/volumeutils.py", line 867, in mount_glusterfs_with_host
    for host in hosts.split(','):
AttributeError: 'NoneType' object has no attribute 'split''

```

kubectl edit configmaps -n kadalu kadalu-info
```  storage-gluster-external.info: '{"volname": "storage-gluster-external", "volume_id":
    "84f3b0a2-0a74-11eb-b7bd-02b48d674b8e", "type": "External", "kadalu-format": true,
    "gluster_host": "gluster0.example.com", "gluster_volname":
    "shared_volume", "gluster_options": "log-level=DEBUG"}'
  storage-ua-gluster-external.info: '{"volname": "storage-ua-gluster-external", "volume_id":
    "96c66c1e-ae45-11eb-ac4f-d2b825d27f5d", "type": "External", "kadalu-format": true,
    "gluster_hosts": "gluster0.second.example.com", "gluster_volname":
    "shared_volume", "gluster_options": "log-level=DEBUG"}'
```
Kubernetes: v1.20.2
GlusterFs 7
Kadalu: devel
