### ISSUE TITLE
 failed to open /proc/0/status: No such file or directory

### ISSUE THREAD

**Issue by pawel-detka** [kadalu/kadalu#540]
Greetings!
So I have super strange issue.
I have two exactly the same clusters (Stage and Prod):

```
NAME                     STATUS   ROLES    AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION               CONTAINER-RUNTIME
ab-k8s-stage2-master-1   Ready    master   74d   v1.19.2   172.20.22.246   <none>        CentOS Linux 7 (Core)   3.10.0-862.14.4.el7.x86_64   docker://19.3.13
ab-k8s-stage2-master-2   Ready    master   74d   v1.19.2   172.20.22.247   <none>        CentOS Linux 7 (Core)   3.10.0-862.14.4.el7.x86_64   docker://19.3.13
ab-k8s-stage2-master-3   Ready    master   74d   v1.19.2   172.20.22.248   <none>        CentOS Linux 7 (Core)   3.10.0-862.14.4.el7.x86_64   docker://19.3.13
ab-k8s-stage2-node-1     Ready    worker   74d   v1.19.2   172.20.22.249   <none>        CentOS Linux 7 (Core)   3.10.0-862.14.4.el7.x86_64   docker://19.3.13
ab-k8s-stage2-node-2     Ready    worker   74d   v1.19.2   172.20.22.250   <none>        CentOS Linux 7 (Core)   3.10.0-862.14.4.el7.x86_64   docker://19.3.13
ab-k8s-stage2-node-3     Ready    worker   74d   v1.19.2   172.20.22.251   <none>        CentOS Linux 7 (Core)   3.10.0-862.14.4.el7.x86_64   docker://19.3.13
```

+ 3x CentOS 7 Gluster 7.

 
Few times a day, on Stage, I see in logs errors:

```
[2021-05-11 08:30:01.522684 +0000] E [fuse-helpers.c:201:frame_fill_groups] 0-fuse: failed to open /proc/0/status: No such file or directory
pending frames:
frame : type(0) op(0)
frame : type(0) op(0)
frame : type(0) op(0)
patchset: git://git.gluster.org/glusterfs.git
signal received: 11
time of crash: 
2021-05-11 08:30:04 +0000
configuration details:
argp 1
backtrace 1
dlfcn 1
libpthread 1
llistxattr 1
setfsid 1
spinlock 1
epoll.h 1
xattr.h 1
st_atim.tv_nsec 1
package-string: glusterfs 2021.02.22
/opt/lib/libglusterfs.so.0(+0x2bc54)[0x7fc1d3555c54]
/opt/lib/libglusterfs.so.0(gf_print_trace+0x486)[0x7fc1d35610b6]
/lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7fc1d32fe210]
/lib/x86_64-linux-gnu/libpthread.so.0(pthread_mutex_lock+0x4)[0x7fc1d34b7fc4]
/opt/lib/libglusterfs.so.0(__gf_free+0x11d)[0x7fc1d357f4ad]
/opt/lib/glusterfs/2021.02.22/xlator/cluster/replicate.so(+0x67f40)[0x7fc1cdfa7f40]
/opt/lib/glusterfs/2021.02.22/xlator/cluster/replicate.so(+0x67fc8)[0x7fc1cdfa7fc8]
/opt/lib/glusterfs/2021.02.22/xlator/cluster/replicate.so(+0x67fdd)[0x7fc1cdfa7fdd]
/opt/lib/libglusterfs.so.0(fd_unref+0x11f)[0x7fc1d357cc1f]
/opt/lib/glusterfs/2021.02.22/xlator/mount/fuse.so(+0x203d3)[0x7fc1d21693d3]
/opt/lib/glusterfs/2021.02.22/xlator/mount/fuse.so(+0x1de67)[0x7fc1d2166e67]
/opt/lib/glusterfs/2021.02.22/xlator/mount/fuse.so(+0x2448c)[0x7fc1d216d48c]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x9609)[0x7fc1d34b5609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7fc1d33da293]
```

on different nodes. This is crucshing my application, to fix it temporarly I need to restart pod(s) kadalu-csi-nodeplugin-xxx and restart application pod. 

On Production however everything is working as charm, Uptime now is about 3 month without any issue.

Configuration of Kadalu:

```
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage-gluster-external
spec:
  type: External
  details:
      gluster_hosts:
        - 172.20.22.252
        - 172.20.22.253
        - 172.20.22.254
      gluster_volname: shared_volume
      gluster_options: log-level=DEBUG
```

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-volume-gluster
spec:
  storageClassName: kadalu.external.storage-gluster-external
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 80Gi
```

What I am doing wrong ?
