### ISSUE TITLE
Add pod annotations on kadalu-csi statefulset to allow Prom scraping process

### ISSUE THREAD

**Issue by tili41** [kadalu/kadalu#626]
Hi. It could be useful to add pod annotations on `kadalu-csi-statefulset` to allow Prometheus to autmatically scrape metrics exported by `kadalu-csi-provisionner-0`. It would avoid having to configure Prometheus. Thanks.

```
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kadalu-csi-provisioner
  namespace: {{ namespace }}
(...)
template:
    metadata:
      name: csi-provisioner
      namespace: {{ namespace }}
      labels:
        app.kubernetes.io/part-of: kadalu
        app.kubernetes.io/component: csi-driver
        app.kubernetes.io/name: kadalu-csi-provisioner
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
```
