### ISSUE TITLE
unexpected data beyond EOF in block 

### ISSUE THREAD

**Issue by vincentchong1** [kadalu/kadalu#673]
when trying to insert a > 1 million record, i received above error, and the transaction is not successful.

May I know what could cause the problem described, is there any work around?
```
{"name":"postgresql","image":"docker.io/bitnami/postgresql-repmgr:11.13.0-debian-10-r53"}
{"name":"kadalu-nodeplugin","image":"docker.io/kadalu/kadalu-csi:0.8.4"}
{"name":"kadalu-logging","image":"docker.io/library/busybox"}
{"name":"kadalu-provisioner","image":"docker.io/kadalu/kadalu-csi:0.8.4"}
{"name":"kadalu-operator","image":"docker.io/kadalu/kadalu-operator:0.8.4"}
{"name":"server","image":"docker.io/kadalu/kadalu-server:0.8.4"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

$ uname -r
3.10.0-1160.el7.x86_64
```

**Comment by leelavg** [comment]
- The issue description leaves a lot of room to assume the setup 😅
- We suggest databases to be run on `pv_type: Block` introduced in `v0.8.6`
- We didn't have the infra to perform scale testing, if possible provide a reproducer or all kadalu logs when the transaction didn't succeed and also any required log snippet of postgresql as well

**Comment by vincentchong1** [comment]
as an update, i removed the dependency on kadalu pvc, i can insert > 5 million record without issue.
will see what I can provide in term of logs.
and try out the 0.8.6.

**Comment by leelavg** [comment]
- by removing dependency, do you mean you aren't using Kadalu for above (>5m) operation?

**Comment by vincentchong1** [comment]
@leelavg, yes, just pure bitnami postgresql-ha chart, and not using kadalu pvc at all.

**Comment by vincentchong1** [comment]
what is the setting on performance.stat-prefetch in kadalu implementation.
we will like to have a way to turn it off if it is currently ON
https://docs.openshift.com/container-platform/3.10/scaling_performance/optimizing_on_glusterfs_storage.html#Tested-Applciations
https://access.redhat.com/solutions/3673761

**Comment by leelavg** [comment]
- Uh oh, this might be a long road
- @amarts any chances of increasing priority for #542 ?
- Did you get a chance to try `pv_type: Block`?

**Comment by vincentchong1** [comment]
I have issue using pv_type, still try to figure out how to set it up.
May I know if I can have single disk/volume, and also having 3 different storageclass, that is kadalu, kadalu.kadalu-storage-pool, kadalu.block?  Which configuration set up those storageclass.

**Comment by leelavg** [comment]
- Repeating from existing docs with some emphasis
- Assuming below is the Kadalu CR and you deployed it
``` yaml
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: pool-1
spec:
  type: Replica1
  storage:
    - node: node1
      device: /dev/sda1
    - node: node2
      device: /dev/sda2
    - node: node3
      device: /dev/sda3
```
- You'll be seeing a storage class created out of it with `kadalu.` prefix like, `kadalu.pool-1` and that answers your second question i.e, kadalu sets up those sc based on CR deployed. Storage Class `kadalu` is from older release, if there's no PVC using that it can be safely removed.
- Every supported type of Kadalu volumes have three filters which can be used to create custom storage class like below
``` yaml
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kadalu.example
provisioner: kadalu
parameters:
  # For simplicity I'm stating all supported parameters here itself but you have to choose a specific parameter which can be clubbed with specific kadalu storage cr
  storage_name: pool-1 # States this sc should carve PV from kadalu storage cr named `pool-1` (or you can directly use pre-created `kadalu.pool-1`)
  storage_type: Replica1 # PV should be from kadalu cr which is of `Replica1` type
  pv_type: Block # Resulting PV will be a xfs formatted truncated file
```
- Replica1 gets another parameter `node_affinitiy: node2` and it stated the PV should be from `node2` since Replica1 is pure distributed.
- You can use above according to your usecase which provides flexibility, like you might've a good config node and want to tie some workloads to that and use `node_affinity` or created a pool with fast storage and filter by that name in above sc etc

**Comment by vincentchong1** [comment]
I am not sure which configuration that I missed, can someone give me some pointer?

The problem is none of the kadalu pool are not set up

I use kadalu-operator.yaml and csi-nodeplugin.yaml manifest directly from this site, with devel changed to 0.8.6.

Then, i have the worker /dev/vdc disk set up, and some kadalu configuration below

```
[centos@zc442esmv01kma001 ansible]$ cat /home/centos/manifests/storage-config.yaml
# File: sample-storage-config.yaml
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  # This will be used as name of PV Hosting Volume
  name: kadalu-storage-pool
spec:
  type: Replica1
  storage:
    - node: zc442esmv01kwo001
      device: /dev/vdc
    - node: zc442esmv01kwo002
      device: /dev/vdc

[centos@zc442esmv01kma001 ansible]$ cat /home/centos/manifests/kadalu-storageclass.yaml
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kadalu.storage-pool-1-block
provisioner: kadalu
parameters:
  storage_name: "kadalu-storage-pool"
  pv_type: Block
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-block
spec:
  storageClassName: kadalu.storage-pool-1-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# there are similar pvc-volume1, pvc-volume2, pvc-volume3 below configuration
[centos@zc442esmv01kma001 ansible]$ cat /home/centos/manifests/glusterfs-pvc-volume1.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-volume1
spec:
  storageClassName: kadalu.kadalu-storage-pool
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 500Mi

```

```
[centos@zc442esmv01kma001 ansible]$ kubectl get pod -n kadalu -o wide
NAME                             READY   STATUS    RESTARTS   AGE   IP               NODE                NOMINATED NODE   READINESS GATES
kadalu-csi-nodeplugin-6cc9h      3/3     Running   0          14m   172.16.77.79     zc442esmv01kwo001   <none>           <none>
kadalu-csi-nodeplugin-r48c8      3/3     Running   0          14m   172.16.105.141   zc442esmv01kwo002   <none>           <none>
kadalu-csi-provisioner-0         5/5     Running   0          13m   172.16.105.140   zc442esmv01kwo002   <none>           <none>
operator-68549ffd6b-rclb9        1/1     Running   0          14m   172.16.105.139   zc442esmv01kwo002   <none>           <none>
server-kadalu-storage-pool-0-0   0/1     Running   4          13m   172.16.77.80     zc442esmv01kwo001   <none>           <none>
server-kadalu-storage-pool-1-0   0/1     Running   4          13m   172.16.105.142   zc442esmv01kwo002   <none>           <none>
```
```
[centos@zc442esmv01kma001 ansible]$ kubectl get cm -n kadalu
NAME               DATA   AGE
kadalu-info        3      11m
kube-root-ca.crt   1      11m
```
```
[centos@zc442esmv01kma001 ansible]$ kubectl get storageclass
NAME                          PROVISIONER   RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
kadalu.kadalu-storage-pool    kadalu        Delete          Immediate           true                   11m
kadalu.storage-pool-1-block   kadalu        Delete          Immediate           false                  12m
```
```
[centos@zc442esmv01kma001 ansible]$ ssh kwo1 'lsblk -fp'
NAME        FSTYPE  LABEL      UUID                                 MOUNTPOINT
/dev/sr0    iso9660 config-2   2021-10-27-13-06-50-00
/dev/vda
└─/dev/vda1 xfs                9cff3d69-3769-4ad9-8460-9c54050583f9 /
/dev/vdb    vfat    ephemeral0 DB0E-DD0A                            /mnt
/dev/vdc    xfs                e3b1de56-abbf-48f0-bd32-867922483d31

[centos@zc442esmv01kma001 ansible]$ ssh kwo2 'lsblk -fp'
NAME        FSTYPE  LABEL      UUID                                 MOUNTPOINT
/dev/sr0    iso9660 config-2   2021-10-27-13-08-18-00
/dev/vda
└─/dev/vda1 xfs                9cff3d69-3769-4ad9-8460-9c54050583f9 /
/dev/vdb    vfat    ephemeral0 19F3-B579                            /mnt
/dev/vdc    xfs                5d642a4d-cc82-426e-8699-4f2e27c2300b
```
```
[centos@zc442esmv01kma001 ansible]$ kubectl describe cm kadalu-info -n kadalu
Name:         kadalu-info
Namespace:    kadalu
Labels:       <none>
Annotations:  <none>

Data
====
kadalu-storage-pool.info:
----
{"namespace": "kadalu", "kadalu_version": "0.8.6", "volname": "kadalu-storage-pool", "volume_id": "ad380142-3829-11ec-9fc1-36a93bd00100", "kadalu_format": "native", "type": "Replica1", "pvReclaimPolicy": "delete", "bricks": [{"brick_path": "/bricks/kadalu-storage-pool/data/brick", "kube_hostname": "zc442esmv01kwo001", "node": "server-kadalu-storage-pool-0-0.kadalu-storage-pool", "node_id": "node-0", "host_brick_path": "", "brick_device": "/dev/vdc", "pvc_name": "", "brick_device_dir": "", "decommissioned": "", "brick_index": 0}, {"brick_path": "/bricks/kadalu-storage-pool/data/brick", "kube_hostname": "zc442esmv01kwo002", "node": "server-kadalu-storage-pool-1-0.kadalu-storage-pool", "node_id": "node-1", "host_brick_path": "", "brick_device": "/dev/vdc", "pvc_name": "", "brick_device_dir": "", "decommissioned": "", "brick_index": 1}], "disperse": {"data": 0, "redundancy": 0}, "options": {}}
uid:
----
02dfeb22-b620-4563-bfee-b53a261a619c
volumes:
----

Events:  <none>
```
I am not sure why the AGE Is 4h and 13h, seem like it is left over from prior implementation.
I use below each time I recreate the kadalu
```
curl -s https://raw.githubusercontent.com/kadalu/kadalu/devel/extras/scripts/cleanup | bash
```
```
[centos@zc442esmv01kma001 ansible]$ kubectl get pvc
NAME          STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                  AGE
pv-block      Pending                                      kadalu.storage-pool-1-block   4h33m
pvc-volume1   Pending                                      kadalu-storage-pool           13h
pvc-volume2   Pending                                      kadalu-storage-pool           13h
pvc-volume3   Pending                                      kadalu-storage-pool           13h
```
I think is my misunderstanding on which namespace each object should be created in
```
[centos@zc442esmv01kma001 ansible]$ kubectl get events -A | grep kadalu | grep persistentvolumeclaim
default       4m24s       Normal    ExternalProvisioning   persistentvolumeclaim/pv-block                 waiting for a volume to be created, either by external provisioner "kadalu" or manually created by system administrator
default       54m         Warning   ProvisioningFailed     persistentvolumeclaim/pv-block                 storageclass.storage.k8s.io "kadalu.storage-pool-1-block" not found
default       4m32s       Warning   ProvisioningFailed     persistentvolumeclaim/pv-block                 failed to provision volume with StorageClass "kadalu.storage-pool-1-block": rpc error: code = Unknown desc = Exception calling application: [Errno 107] Transport endpoint is not connected
default       4m54s       Warning   ProvisioningFailed     persistentvolumeclaim/pvc-volume1              storageclass.storage.k8s.io "kadalu-storage-pool" not found
default       4m54s       Warning   ProvisioningFailed     persistentvolumeclaim/pvc-volume2              storageclass.storage.k8s.io "kadalu-storage-pool" not found
default       4m54s       Warning   ProvisioningFailed     persistentvolumeclaim/pvc-volume3              storageclass.storage.k8s.io "kadalu-storage-pool" not found
kadalu        4m39s       Normal    ExternalProvisioning   persistentvolumeclaim/pv-block                 waiting for a volume to be created, either by external provisioner "kadalu" or manually created by system administrator
kadalu        6m42s       Normal    Provisioning           persistentvolumeclaim/pv-block                 External provisioner is provisioning volume for claim "kadalu/pv-block"
kadalu        4m32s       Warning   ProvisioningFailed     persistentvolumeclaim/pv-block                 failed to provision volume with StorageClass "kadalu.storage-pool-1-block": rpc error: code = Unknown desc = Exception calling application: [Errno 107] Transport endpoint is not connected
```

```
[centos@zc442esmv01kma001 ansible]$ kubectl get pvc -A
NAMESPACE   NAME          STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                  AGE
default     pv-block      Pending                                      kadalu.storage-pool-1-block   5h5m
default     pvc-volume1   Pending                                      kadalu-storage-pool           13h
default     pvc-volume2   Pending                                      kadalu-storage-pool           13h
default     pvc-volume3   Pending                                      kadalu-storage-pool           13h
kadalu      pv-block      Pending                                      kadalu.storage-pool-1-block   50m
```

yaml files are apply using below ansible playbook
```
- name: Apply Kadalu manifest in Kubernetes to deploy Endpoints
  become_user: "{{ cloud_user }}"
  k8s:
    state: present
    src: "/home/{{ cloud_user }}/manifests/{{ item }}"
    namespace: kadalu
  with_items:
    - kadalu-operator.yaml_0.8.6
    - csi-nodeplugin.yaml_0.8.6
    - storage-config.yaml
    - kadalu-storageclass.yaml
```
