### ISSUE TITLE
Support for Replica1 to Replica3 migration

### ISSUE THREAD

**Issue by MatteoManzoni** [kadalu/kadalu#714]
Hello all!
I've experimented a little bit with Kadalu and everything seems really good moreover the performances are great compared to other CAS/CSI supporting RWX.
During my experimentations I've found an issue, maybe it is related to my specific use case, I know a thing or two about GlusterFS and I've done volume replica addition in the past.
To reproduce the issue:
- Create a single node cluster and install Kadalu
- Create a KadaluStorage resource with the following manifest:
``` yaml
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage01
  namespace: kadalu
spec:
  type: Replica1
  pvReclaimPolicy: archive
  storage:
    - node: node1
      device: /dev/kadalu/kadalu
```
- Create PVCs, Test Kadalu, everything ok
- Join some more nodes to the cluster
- Apply/Patch KadaluStorage with the following manifest in order to achieve Replication across nodes:
``` yaml
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage01
  namespace: kadalu
spec:
  type: Replica3
  pvReclaimPolicy: archive
  storage:
    - node: node1
      device: /dev/kadalu/kadalu
    - node: node2
      device: /dev/kadalu/kadalu
    - node: node3
      device: /dev/kadalu/kadalu
```
- The KadaluStorage shows Replica3
- `kubectl kadalu healinfo` says: `This command is supported for only volumes of replicate/disperse type. Volume storage01 is not of type replicate/disperse`

Let me know if I can do something more to help you understand my issue!
