### ISSUE TITLE
jaeger writes logs outside the brick folder

### ISSUE THREAD

**Issue by NawiLan** [kadalu/kadalu#752]
Hello, jaeger writes logs outside the brick folder, although he should log inside pv. Version kadalu 0.8.9. Config jaeger [values.txt](https://github.com/kadalu/kadalu/files/7903973/values.txt)

![image](https://user-images.githubusercontent.com/65493277/150313418-9a64918e-a2a8-407f-953f-e33756523042.png)

Kadalu config
```
apiVersion:` kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  # This will be used as name of PV Hosting Volume
  name: kadalu-gluster
spec:
  kadalu_format: native
  type: Replica3
  pvReclaimPolicy: archive # delete for ex.
  storage:
    - node: kub-prod-worker01
      device: /dev/sda3
    - node: kub-prod-worker02
      device: /dev/sda3
    - node: kub-prod-worker03
      device: /dev/sdb1
```

**Comment by leelavg** [comment]
1. Is backtick after `apiVersion` a typo while copying the manifest?
2. Manifest corresponds to storage class mentioned in jaeger values `kadalu.kadalu-gluster`
3. But it doesn't match with snap `/mnt/kub-glusterfs` and how did you mount gluster on master node?

Could you please cross check info once?

**Comment by NawiLan** [comment]
1. Yes. sorry
2. Yes, it matches
3. ![image](https://user-images.githubusercontent.com/65493277/150323123-b26b07aa-3655-4273-ac71-626f1fc8e11e.png)

Sorry, correct config is here
```
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  # This will be used as name of PV Hosting Volume
  name: kadalu-gluster
spec:
  kadalu_format: native
  type: Replica3
  pvReclaimPolicy: archive # delete for ex.
  storage:
    - node: kub-master01
      device: /dev/sdb1
    - node: kub-worker01
      device: /dev/sdb1
    - node: kub-worker02
      device: /dev/sdb1
```
