### ISSUE TITLE
Cant use storage classes with kadalu

### ISSUE THREAD

**Issue by Y0ngg4n** [kadalu/kadalu#756]
![image](https://user-images.githubusercontent.com/30302975/152065780-1fc73fec-3748-447e-a71c-ebf5004c8eb6.png)

PersistentVolume claim gets never ready
```
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: k-dist
spec:
  type: External
  # Omitting 'kadalu_format' or using 'native' as a value will create
  # 1 PV : 1 Subdir in external gluster volume
  kadalu_format: native
  details:
    # gluster_hosts: [ gluster1.kadalu.io, gluster2.kadalu.io ]
    # gluster_host: gluster1.kadalu.io
    gluster_hosts: [ glusterfs-01, glusterfs-02, glusterfs-03 ]
    gluster_volname: k-dist
    gluster_options: log-level=DEBUG
```
