### ISSUE TITLE
External Sorage not working

### ISSUE THREAD

**Issue by Y0ngg4n** [kadalu/kadalu#759]
Hi i am running Kadalu on a virtualized k8s Kubernetes Cluster with Debian VMs.
This are my storage classes:
```
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: k-dist
spec:
  type: External
  # Omitting 'kadalu_format' or using 'native' as a value will create
  # 1 PV : 1 Subdir in external gluster volume
  kadalu_format: native
  details:
    # gluster_hosts: [ gluster1.kadalu.io, gluster2.kadalu.io ]
    # gluster_host: gluster1.kadalu.io
    gluster_hosts: [ glusterfs-01, glusterfs-02, glusterfs-03 ]
    gluster_volname: k-dist
    gluster_options: log-level=DEBUG

---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: k-repl
spec:
  type: External
  # Omitting 'kadalu_format' or using 'native' as a value will create
  # 1 PV : 1 Subdir in external gluster volume
  kadalu_format: native
  details:
    # gluster_hosts: [ gluster1.kadalu.io, gluster2.kadalu.io ]
    # gluster_host: gluster1.kadalu.io
    gluster_hosts: [ glusterfs-01, glusterfs-02, glusterfs-03 ]
    gluster_volname: k-repl
    gluster_options: log-level=DEBUG
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: k-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
spec:
  type: External
  # Omitting 'kadalu_format' or using 'native' as a value will create
  # 1 PV : 1 Subdir in external gluster volume
  kadalu_format: native
  details:
    # gluster_hosts: [ gluster1.kadalu.io, gluster2.kadalu.io ]
    # gluster_host: gluster1.kadalu.io
    gluster_hosts: [ glusterfs-01, glusterfs-02, glusterfs-03 ]
    gluster_volname: k-sc
    gluster_options: log-level=DEBUG
```
mount of gluster volumes work on other hosts.
But when trying to create a pvc i get this events:
![image](https://user-images.githubusercontent.com/30302975/152248091-25a29777-019e-4d40-8e92-d5da8be93eaa.png)

If you need more information don´t hestitate to ask.
