### ISSUE TITLE
[Bug]: kadalu_memory_usage_in_bytes is -1 in Openshift/OKD

### ISSUE THREAD

**Issue by hunter86bg** [kadalu/kadalu#810]
**Describe the bug**
On OKD4.10 (but should be valid for Openshift/OKD 4.8+) cgroup2 is used . This leads to missing "/sys/fs/cgroup/memory/memory.usage_in_bytes" on the pods and the metric 'kadalu_memory_usage_in_bytes' is presented as "-1".

**To Reproduce**
1. Enable user workload metrics 
2. Apply the following manifest:
```
---
kind: Namespace
apiVersion: v1
metadata:
  name: kadalu
  labels:
    openshift.io/cluster-monitoring: "true"
---
kind: Service
apiVersion: v1
metadata:
  name: operator
  namespace: kadalu
  labels:
    name: kadalu
spec:
  selector:
    name: kadalu
  ports:
    - name: kadalu-metrics
      protocol: TCP
      port: 8050
      targetPort: 8050
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kadalu-metrics
  namespace: kadalu
  labels:
    name: kadalu
spec:
  endpoints:
    - path: /metrics
      port: kadalu-metrics
      scheme: http
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      name: kadalu
```
3. Set necessary permissions:
```
oc policy add-role-to-user kadalu-operator system:serviceaccount:openshift-monitoring:prometheus-k8s -n kadalu
```

**Expected behavior**
kadalu_memory_usage_in_bytes should present actual data or be removed.

**Actual behavior**
The metrics is logging in Openshift/OKD with value of "-1".

**Environment:**
1. 
```
$ kubectl-kadalu version
kubectl-kadalu plugin: 0.8.14
kadalu pod(s) versions
pod/kadalu-csi-nodeplugin-j9twl: 0.8.14
pod/kadalu-csi-nodeplugin-nrhm9: 0.8.14
pod/kadalu-csi-provisioner-0: 0.8.14
pod/operator-54696d985f-5wgdk: 0.8.14
pod/server-gluster-0-0: 0.8.14
pod/server-gluster-1-0: 0.8.14
pod/server-gluster-2-0: 0.8.14
```
2. 
```
$ oc adm upgrade
Cluster version is 4.10.0-0.okd-2022-04-23-131357
```
