### ISSUE TITLE
[Bug]: Kadalu provisioner logs 8 empty lines every few seconds

### ISSUE THREAD

**Issue by Timoses** [kadalu/kadalu#837]
**Describe the bug**
```
> k -n kadalu logs -f kadalu-csi-provisioner-0 -c kadalu-provisioner | cat -e
...
$
$
$
$
$
$
$
$
$
$
```

**To Reproduce**
1. Install v0.8.14 via releases manifests
2. Deploy Storage:
    ```
    apiVersion: kadalu-operator.storage/v1alpha1
    kind: KadaluStorage
    metadata:
      name: storage
      namespace: kadalu
    spec:
      pvReclaimPolicy: archive
      storage:
      - device: /dev/sda
        node: t5s-1
      - device: /dev/sda
        node: t5s-2
      - device: /dev/sda
        node: t5s-3
      type: Replica3
    ```
4. View logs `k -n kadalu logs -f kadalu-csi-provisioner-0 -c kadalu-provisioner`

**Expected behavior**
It should not print empty lines.

**Actual behavior**
It prints empty 8 lines consistently about every 5 seconds

**Environment:**
$ kubectl exec -it deploy/operator -n kadalu -- bash -c 'kubectl-kadalu version'
```
kubectl-kadalu plugin: 0.8.14
kadalu pod(s) versions
pod/kadalu-csi-nodeplugin-86pvs: 0.8.14
pod/kadalu-csi-nodeplugin-8vc4p: 0.8.14
pod/kadalu-csi-nodeplugin-zt94v: 0.8.14
pod/kadalu-csi-provisioner-0: 0.8.14
pod/operator-7579546f7-thrxm: 0.8.14
pod/server-storage-0-0: 0.8.14
pod/server-storage-1-0: 0.8.14
pod/server-storage-2-0: 0.8.14
```
 - Kadalu Version: 0.8.14
 - K8S_DIST: kubernetes

**Screenshots or Logs**
See above.

**Additional context**
Talos K8s cluster on 3 Raspberry Pi 4s
