### ISSUE TITLE
[Bug]: storageclass.storage.k8s.io "kadalu.ext-conf" not found

### ISSUE THREAD

**Issue by ghost** [kadalu/kadalu#856]
Hello dear community!

Steps to reproduce the problem:

1. Install GlusterFS in three nodes (2 replica + 1 arbiter).
2. Create K8s cluster (kind used).
3. Kadalu installed.
4. Created KadaluStorage:

```yaml
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: ext-conf
spec:
  type: External
  details:
    gluster_host: "[ 10.0.2.119, 10.0.2.120, 10.0.2.121 ]"
    gluster_volname: gluster-test
    gluster_options: log-level=DEBUG
```

5. Created PVC:

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ext-pvc
spec:
  storageClassName: kadalu.ext-conf
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
```

Expected: working PVC.

Actual:

```bash
ser@host:~$ kubectl describe pvc ext-pvc
Name:          ext-pvc
Namespace:     default
StorageClass:  kadalu.ext-conf
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason              Age                   From                         Message
  ----     ------              ----                  ----                         -------
  Warning  ProvisioningFailed  78s (x26 over 7m23s)  persistentvolume-controller  storageclass.storage.k8s.io "kadalu.ext-conf" not found
```

**Environment:**

```bash
user@host:~$ kubectl kadalu version
kubectl-kadalu plugin: 0.8.15
kadalu pod(s) versions
pod/kadalu-csi-nodeplugin-8c7th: 0.8.15
pod/kadalu-csi-nodeplugin-gdlnr: 0.8.15
pod/kadalu-csi-provisioner-0: 0.8.15
pod/operator-57b47b555f-r4wrd: 0.8.15
```

Thanks a lot for the help!
