### ISSUE TITLE
Transport Endpoint Not connected

### ISSUE THREAD

**Issue by bodleytunes** [kadalu/kadalu#857]
Hi All,

I seem to have hit a snag where when I delete namespace with a load of PVC's, when I recreate the namespace, the storage hangs and the PV's are not created.

I can see the error "transport endpoint not connected" for the PVC's

```
failed to provision volume with StorageClass "kadalu.critical": rpc error: code = Unknown desc = Exception calling application: [Errno 107] Transport endpoint is not connected
```

Other than I don't really know why it fails to recreate the PV's.

Any ideas where to look or what to check?

my storage classes were created as follows:

```
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
# This will be used as name of PV Hosting Volume
  name: standard
spec:
  type: Replica1
  pvReclaimPolicy: archive
  storage:
    - node: rancher2
      path: /var/lib/kadalu/standard
```

Many thanks,

Jon.
