### ISSUE TITLE
[Bug]: Tolerate may not work or I just do not get it

### ISSUE THREAD

**Issue by a10sbraun** [kadalu/kadalu#867]
**Describe the bug**
Replica3 does not work as I the pool will not be scheduled to the master (toleration seems not to work) and will not be applied to the pool pods.

Replica2 (my favorite) the pool keeps restarting and crashing, also I do not know if I have to setup the tie-breaker or not, as the description is not really available. I would expect from the operator to setup the tie-breaker which in this case should be my master as well.

I also would like to have the provisioner on my master, but again toleration are missing. 

In general I would like to have a custom resource file where I can configure the operator in the way I need it to gain more flexibility.

Calico has found a nice way to do it for Tigera 
apiVersion: operator.tigera.io/v1
kind: Installation

So for Kadula
```
apiVersion: operator.kadula.io/v1
kind: Installation
metadata:
  name: default
spec:
  provisoner:
  - master: yes/no # default no
  - toleration: key:operator:value # default empty
  - affinity: node/label # default empty
  - selector: label xyz # default empty
  tiebreaker:
  - master: yes/no # default no
  - hosted: internal/external/manual # default internal
  - toleration: key:operator:value # default empty
  - affinity: node/label # default empty
  - selector: label xyz # default empty
```

can be used for everything else as well, as it is easy to expand as needed...

**To Reproduce**
Try to use it on a default 3-node cluster (1 master, 2 nodes

**Expected behavior**
I would like to have the meta data on my master (less space / disk needed)

**Actual behavior**
Kadalu is not working as long as I have the master taint

**Environment:**

KVM
Suse Leap Micro 5.2
K3s

kubectl kadalu version
kubectl-kadalu plugin: 0.8.15
kadalu pod(s) versions
pod/kadalu-csi-nodeplugin-qs8fh: 0.8.15
pod/operator-d5586b749-4chr5: 0.8.15
pod/kadalu-csi-nodeplugin-j5x7h: 0.8.15
pod/kadalu-csi-provisioner-0: 0.8.15
pod/kadalu-csi-nodeplugin-w6dtt: 0.8.15

**Screenshots or Logs**

```
cat storageclass.yaml 
apiVersion: "kadalu-operator.storage/v1alpha1"
kind: "KadaluStorage"
metadata:
  name: "storage-pool1"
spec:
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  type: "Replica2"
  storage:
    - node: "micro-n1"
      device: "/dev/loop0"
    - node: "micro-n2"
      device: "/dev/loop0"
  tiebreaker:
    node: "micro-master"
    path: "/dev/loop0"
#  pvReclaimPolicy: retain
```

```
k get pods -A -o wide
NAMESPACE          NAME                                       READY   STATUS             RESTARTS         AGE     IP              NODE           NOMINATED NODE   READINESS GATES
calico-system      calico-node-n2bhq                          1/1     Running            0                6h48m   10.10.10.10     micro-master   <none>           <none>
tigera-operator    tigera-operator-5f9bdc5c59-kthm4           1/1     Running            0                6h44m   10.10.10.10     micro-master   <none>           <none>
kadalu             kadalu-csi-nodeplugin-qs8fh                3/3     Running            0                5h39m   172.20.0.21     micro-master   <none>           <none>
kadalu             operator-d5586b749-4chr5                   1/1     Running            1 (114m ago)     5h46m   172.20.67.158   micro-n1       <none>           <none>
calico-system      calico-typha-8766c44fd-4pxf7               1/1     Running            5 (114m ago)     23h     10.10.10.20     micro-n1       <none>           <none>
kadalu             kadalu-csi-nodeplugin-j5x7h                3/3     Running            3 (114m ago)     5h39m   172.20.67.162   micro-n1       <none>           <none>
kadalu             kadalu-csi-provisioner-0                   5/5     Running            5 (114m ago)     5h46m   172.20.67.160   micro-n1       <none>           <none>
calico-apiserver   calico-apiserver-74cdbc988d-tncpg          1/1     Running            9 (114m ago)     23h     172.20.67.161   micro-n1       <none>           <none>
calico-system      calico-node-8rzzs                          1/1     Running            5 (114m ago)     23h     10.10.10.20     micro-n1       <none>           <none>
kube-system        local-path-provisioner-6c79684f77-fdlkc    1/1     Running            5 (36m ago)      24h     172.20.166.41   micro-n2       <none>           <none>
calico-system      calico-typha-8766c44fd-v24ll               1/1     Running            5 (36m ago)      23h     10.10.10.30     micro-n2       <none>           <none>
calico-apiserver   calico-apiserver-74cdbc988d-k5jxr          1/1     Running            1 (36m ago)      6h45m   172.20.166.44   micro-n2       <none>           <none>
kube-system        coredns-d76bd69b-nmc4s                     1/1     Running            5 (36m ago)      24h     172.20.166.45   micro-n2       <none>           <none>
calico-system      calico-kube-controllers-54fcfcd697-d6xgv   1/1     Running            7 (36m ago)      23h     172.20.166.42   micro-n2       <none>           <none>
kadalu             kadalu-csi-nodeplugin-w6dtt                3/3     Running            3 (36m ago)      5h38m   172.20.166.43   micro-n2       <none>           <none>
calico-system      calico-node-xmq6x                          1/1     Running            5 (36m ago)      23h     10.10.10.30     micro-n2       <none>           <none>
kube-system        metrics-server-7cd5fcb6b7-pplwg            1/1     Running            5 (36m ago)      24h     172.20.166.46   micro-n2       <none>           <none>
kadalu             server-storage-pool1-1-0                   0/1     CrashLoopBackOff   14 (4m27s ago)   47m     172.20.166.47   micro-n2       <none>           <none>
kadalu             server-storage-pool1-0-0                   0/1     CrashLoopBackOff   7 (2m5s ago)     24m     172.20.67.167   micro-n1       <none>           <none>
```

```
k get nodes -o wide
NAME           STATUS   ROLES                  AGE   VERSION        INTERNAL-IP   EXTERNAL-IP       OS-IMAGE                  KERNEL-VERSION                CONTAINER-RUNTIME
micro-n1       Ready    <none>                 24h   v1.23.8+k3s2   10.10.10.20   192.168.108.101   openSUSE Leap Micro 5.2   5.3.18-150300.59.76-default   containerd://1.5.13-k3s1
micro-master   Ready    control-plane,master   24h   v1.23.8+k3s2   10.10.10.10   192.168.108.100   openSUSE Leap Micro 5.2   5.3.18-150300.59.76-default   containerd://1.5.13-k3s1
micro-n2       Ready    <none>                 24h   v1.23.8+k3s2   10.10.10.30   192.168.108.102   openSUSE Leap Micro 5.2   5.3.18-150300.59.76-default   containerd://1.5.13-k3s1
```
