### ISSUE TITLE
[Bug]: How to modify Dockfile for sample-app failed？

### ISSUE THREAD

**Issue by abelard2008** [kadalu/kadalu#872]
in Kubernetes' master, I got :
```
[root@pcz-gluster-101 kadalu]# kubectl get pods -n kadalu
NAME                          READY   STATUS    RESTARTS        AGE
kadalu-csi-nodeplugin-d5qgp   3/3     Running   4       (2d21h ago)   3d6h
kadalu-csi-nodeplugin-vdcwp   3/3     Running   3       (2d21h ago)   3d6h
kadalu-csi-provisioner-0       5/5     Running   0               2d21h
operator-785fdcc79-lhvbq     1/1      Running   2        (2d21h ago)   3d6h
server-storage-pool-1-0-0     1/1      Running   0                2d18h
```
But my sample-app failed:
```
[root@pcz-gluster-102 ~]# docker run -it docker.io/kadalu/sample-pv-check-app bash
This is a sample application
# df -h
Filesystem                Size      Used Available Use% Mounted on
df: /mnt/pv: can't find mount point
FAILURE
# mount
Write/Read test on PV mount
/kadalu/script.sh: line 13: /mnt/pv/timestamp: No such file or directory
Write FAILURE
cat: can't open '/mnt/pv/timestamp': No such file or directory
Read FAILURE
rm: can't remove '/mnt/pv/timestamp': No such file or directory
FAILURE
```
I don't know how to correct it,  also, where to find "mount ... /mnt/pv" command?

Best REGARDS

**Comment by leelavg** [comment]
1. PVC claim should exists in sample app at specific location before it should be run
2. ptal at https://github.com/kadalu/kadalu/tree/devel/extras/sample-app

**Comment by vatsa287** [comment]
@abelard2008 Please check 
` $ kubectl get pvc`, pvc is found & use its name in pvc fle under `claimName` section.

**Comment by abelard2008** [comment]
@vatsa287 
```
[root@pcz-gluster-101 kadalu]# kubectl apply -f sample-pvc.yaml 
persistentvolumeclaim/pv1 created
[root@pcz-gluster-101 kadalu]# kubectl get pvc
NAME   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS            AGE
pv1    Bound    pvc-92231916-f608-48d8-b02c-36847c19a555   1Gi        RWO            kadalu.storage-pool-1   5s
[root@pcz-gluster-101 kadalu]# 
```
After that, I exec `kubectl apply -f sample-app.yaml`?
The following is content of `sample-app.yaml`:
```
# file: sample-app.yaml
---
apiVersion: v1
kind: Pod
metadata:
   name: pod1
   labels:
      app: sample-app
spec:
   containers:
   - name: sample-app
     image: docker.io/kadalu/sample-pv-check-app:latest
     imagePullPolicy: IfNotPresent
     volumeMounts:
     - mountPath: "/mnt/pv"
       name: csivol
   volumes:
   - name: csivol
     persistentVolumeClaim:
         claimName: pv1
   restartPolicy: OnFailure
``` 
right? 

But after `kubectl apply -f sample-app.yaml`, I still got:
```
[root@pcz-gluster-102 ~]# docker run -it docker.io/kadalu/sample-pv-check-app bash
This is a sample application
# df -h
Filesystem                Size      Used Available Use% Mounted on
df: /mnt/pv: can't find mount point
FAILURE
# mount
Write/Read test on PV mount
/kadalu/script.sh: line 13: /mnt/pv/timestamp: No such file or directory
Write FAILURE
cat: can't open '/mnt/pv/timestamp': No such file or directory
Read FAILURE
rm: can't remove '/mnt/pv/timestamp': No such file or directory
FAILURE
[root@pcz-gluster-102 ~]# docker run -it docker.io/kadalu/sample-pv-check-app bash
This is a sample application
# df -h
Filesystem                Size      Used Available Use% Mounted on
df: /mnt/pv: can't find mount point
FAILURE
# mount
Write/Read test on PV mount
/kadalu/script.sh: line 13: /mnt/pv/timestamp: No such file or directory
Write FAILURE
cat: can't open '/mnt/pv/timestamp': No such file or directory
Read FAILURE
rm: can't remove '/mnt/pv/timestamp': No such file or directory
FAILURE
[root@pcz-gluster-102 ~]# docker ps -a | grep sample
4e7bac970ef0        docker.io/kadalu/sample-pv-check-app   "bash /kadalu/scri..."   20 seconds ago       Exited (1) 17 seconds ago                       zen_hamilton
```
Thank you !

**Comment by leelavg** [comment]
> [root@pcz-gluster-102 ~]# docker run -it docker.io/kadalu/sample-pv-check-app bash
- shouldn't is be `kubectl logs sample-app` @abelard2008 ?

**Comment by abelard2008** [comment]
> * kubectl logs sample-app
```
[root@pcz-gluster-101 kadalu]# kubectl apply -f sample-app.yaml 
pod/pod1 created
[root@pcz-gluster-101 kadalu]# kubectl logs sample-app
Error from server (NotFound): pods "sample-app" not found
[root@pcz-gluster-101 kadalu]# 
```

**Comment by leelavg** [comment]
- it should be `kubectl logs pod1` as per your yaml manifest, I meant `sample-app` as placeholder 😅

**Comment by abelard2008** [comment]
@leelavg Sorry，^_^
```
[root@pcz-gluster-101 kadalu]# kubectl logs pod1
This is a sample application
# df -h
Filesystem                Size      Used Available Use% Mounted on
kadalu:storage-pool-1
                          1.0G         0      1.0G   0% /mnt/pv
# mount
kadalu:storage-pool-1 on /mnt/pv type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)
Write/Read test on PV mount
Mon Aug  1 09:36:40 UTC 2022
SUCCESS
```

**Comment by leelavg** [comment]
- there you have it, everything's working as expected
- what's your expectation apart from above and you shouldn't be running `docker run` when you actually deployed an app using `kubectl` those two are mutually exclusive.

**Comment by abelard2008** [comment]
@leelavg Thank you for your patience. Based on your comment above!
I create another sample:
```
[root@pcz-gluster-101 kadalu]# cat ./sample-use-pvc.yaml 
# file: sample-app.yaml
---
apiVersion: v1
kind: Pod
metadata:
   name: pod-taocloudx
   labels:
      app: sample-use-pvc
spec:
   containers:
   - name: sample-use-pvc
     image: busybox
     command:
     - sleep
     - "7200"
     imagePullPolicy: IfNotPresent
     volumeMounts:
     - mountPath: "/mnt/pv"
       name: gluster-volume
   volumes:
   - name: gluster-volume
     persistentVolumeClaim:
         claimName: pv1
   restartPolicy: OnFailure
```
I exec `kubectl apply -f sample-use-pvc.yaml`
the results for `kubectl get pods`
```
[root@pcz-gluster-101 kadalu]# kubectl get pods
NAME                     READY   STATUS      RESTARTS       AGE
pod-taocloudx            1/1     Running     0              5m46s
```
and exec `kubectl exec -ti pod-taocloudx -- /bin/sh`
and `df -Th` after entering into the terminal:
```
/ # df -h
/ # df -Th
Filesystem           Type            Size      Used Available Use% Mounted on
overlay              overlay        27.8G      3.9G     23.9G  14% /
tmpfs                tmpfs           7.8G         0      7.8G   0% /dev
tmpfs                tmpfs           7.8G         0      7.8G   0% /sys/fs/cgroup
kadalu:storage-pool-1  fuse.glusterfs   1.0G         0      1.0G   0% /mnt/pv
```
Right?
