### ISSUE TITLE
[Bug]: Released YAMLs use `devel` images

### ISSUE THREAD

**Issue by Santobert** [kadalu/kadalu#887]
**Describe the bug**
The released YAML files (https://github.com/kadalu/kadalu/releases/tag/0.8.16) use container images with the `devel` tag.

```yaml
        - name: kadalu-operator
          securityContext:
            capabilities: {}
            privileged: true
          image: docker.io/kadalu/kadalu-operator:devel
          imagePullPolicy: IfNotPresent
          env:
```

**To Reproduce**
1. Download YAMLs from the latest release
2. Proceed according to the docs https://github.com/kadalu/kadalu/blob/devel/doc/upgrade.adoc
3. `kubectl-kadalu version`

```
kubectl-kadalu plugin: 0.8.16
kadalu pod(s) versions
pod/kadalu-csi-nodeplugin-pm7rq: devel
pod/kadalu-csi-nodeplugin-tnrms: devel
pod/kadalu-csi-nodeplugin-x29zs: devel
pod/kadalu-csi-provisioner-0: devel
pod/operator-6c7c7b5797-9mxsh: devel
pod/server-storage-pool-1-0-0: devel
pod/server-storage-pool-1-1-0: devel
pod/server-storage-pool-1-2-0: devel
```

**Expected behavior**
YAMLs from version 0.8.16 use container images with the corresponding tag

**Actual behavior**
YAMLs from version 0.8.16 use container images with the `devel` tag

**Environment:**

 - Kadalu Version: 0.8.16
 - K8S_DIST: kubernetes

**Screenshots or Logs**
If applicable, add any screenshots to help explain your problem. Try capturing relevant logs, post them to http://gist.github.com/ and post the links in the issue.

**Additional context**
