### ISSUE TITLE
[Bug]: kubectl kadalu remove-archived-pv returns: Failed to request deletion of archived pvc of the storage

### ISSUE THREAD

**Issue by Timoses** [kadalu/kadalu#912]
**Describe the bug**
Running `k kadalu remove-archived-pv --verbose storage` returns:
```
Failed to request deletion of archived pvc of the storage "storage"
error 1 command terminated with exit code 1
```

**To Reproduce**
1. Apply
```
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage
  namespace: kadalu
spec:
  pvReclaimPolicy: archive
  storage:
  - device: /dev/sda
    node: t5s-1
  - device: /dev/sda
    node: t5s-2
  - device: /dev/sda
    node: t5s-3
  type: Replica3
```
2. Create some PVCs, and remove them again.
3. 
```
> kubectl kadalu storage-list --status

Name             Type        Utilization            Pvs Count      Min PV Size      Avg PV Size      Max PV Size
storage          Replica3    100 Gi/216 Gi (46%)           13             5 Gi             7 Gi            10 Gi

> kubectl get pvc --all-namespaces | awk '{print $1 "    " $2}'
NAMESPACE    NAME
loki    loki
monitoring    prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0
monitoring    prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-1
nextcloud    data-nextcloud-postgresql-0
nextcloud    nextcloud-nextcloud
```
5. `kubectl kadalu remove-archived-pv storage`

**Expected behavior**
It should remove existing archives.

**Actual behavior**
It fails.

**Environment:**
> kubectl kadalu version
kubectl-kadalu plugin: 0.8.16
kadalu pod(s) versions
pod/kadalu-csi-nodeplugin-6qn72: 0.8.16
pod/kadalu-csi-nodeplugin-l6fm5: 0.8.16
pod/kadalu-csi-nodeplugin-tvcnt: 0.8.16
pod/kadalu-csi-provisioner-0: 0.8.16
pod/operator-6c7dc84956-7bs8p: 0.8.16
pod/server-storage-0-0: 0.8.16
pod/server-storage-1-0: 0.8.16
pod/server-storage-2-0: 0.8.16
 - K8S_DIST: kubernetes

**Screenshots or Logs**
See above.

**Additional context**
It's difficult to guess what is actually going on. My guess is with `kadalu --status` I get the number of current and archived PVCs (number is 13, though only 5 are active). So I guess 8 are archived PV(C)s? Do they use up storage space?
