### ISSUE TITLE
[RFE]: Mounting provisioned volumes outside of cluster

### ISSUE THREAD

**Issue by junaru** [kadalu/kadalu#961]
Hello,

Is there a way to mount kadalu initialised volumes outside of the cluster? For example for seeding provisioned pv's with initial data

Looking for something among the lines of:

`mount -t glusterfs <node.ip>:/something /mnt`

Executed on a remote host so i can manipulate the files within.

I guess id like to know if kadalu is listening on all interfaces and how could i authorise and use them from remote host.

Best regards, Justin

**Comment by aravindavk** [comment]
It is not possible with the current version.

- `<node.ip>` may be different than accessing within the K8s cluster
- No glusterd exists to serve the volfiles (Config files) that is required to mount the Volume from outside.

It may be possible with future versions since Volfile server is integrated with server processes itself. So the second problem listed above will go away. For the first problem, create alias for node names(server pod names) to actual IP in `/etc/hosts`.

We will update once the Volfile server feature is ready to use.

**Comment by amoravek** [comment]
I also needed to expose Kadalu RWX  volume via NFS - I've used k8s.gcr.io/volume-nfs image to create NFS server inside the same namespace:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
      - image: k8s.gcr.io/volume-nfs:0.8
        imagePullPolicy: IfNotPresent
        name: nfs-server
        ports:
        - containerPort: 2049
          name: nfs
          protocol: TCP
        - containerPort: 20048
          name: mountd
          protocol: TCP
        - containerPort: 111
          name: rpcbind
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /exports
          name: nfs-data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs-data
        persistentVolumeClaim:
          claimName: <kadalu pvc name>
```

to mount the volume I put this into my fstab:

```
<node ip>:/ /mnt  nfs4 rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=32279,timeo=600,retrans=2,sec=sys,local_lock=none,addr=<node ip> 0 0
```
